# XLSR wav2vec - ASVspoof 5

In [1]:
import pandas as pd

In [2]:
import tensorflow as tf

2025-11-09 20:18:44.184809: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-09 20:18:44.229043: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-09 20:19:12.468523: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [ ]:
#import torch

In [40]:
pd

In [6]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy<2,>=1.21 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install -U scikit-learn scipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: scipy in /home/zkhanja1/.local/lib/python3.11/site-packages (1.15.2)
Collecting scipy
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 58.2 MB/s eta 0:00:00:00:0100:01
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
Successfully installed scipy-1.15.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install librosa

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: librosa in /home/zkhanja1/.local/lib/python3.11/site-packages (0.11.0)
Requirement already satisfied: audioread>=2.1.9 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (3.0.1)
Requirement already satisfied: numba>=0.51.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.59.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.15.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.2.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (5.1.1)
Requirement already satisfied: soundfile>=0.12.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.5.0.post1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (4.9.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.3)
Requirement already satisfied: msgpack>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.0.3)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.51.0->librosa) (0.42.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (3.10.0)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (23.1)
Requirement already satisfied: requests>=2.19.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (2.31.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from soundfile>=0.12.1->librosa) (1.16.0)
Requirement already satisfied: pycparser in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2024.2.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install resampy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: resampy in /home/zkhanja1/.local/lib/python3.11/site-packages (0.4.3)
Requirement already satisfied: numpy>=1.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (1.26.4)
Requirement already satisfied: numba>=0.53 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (0.59.0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.53->resampy) (0.42.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install tf_slim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tf_slim in /home/zkhanja1/.local/lib/python3.11/site-packages (1.1.0)
Requirement already satisfied: absl-py>=0.2.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from tf_slim) (2.2.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from tensorflow.keras.models import Model
from tensorflow.keras import Input
from tensorflow.keras.layers import concatenate, Permute, Reshape
import os

In [4]:
import math
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential

In [5]:
#from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LSTM,TimeDistributed
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [6]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import BatchNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy as np
import sklearn.metrics as metrics

In [7]:
import pandas as pd
import math
import numpy as np
#from numpy.lib.function_base import average
import os
import librosa
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras import models, layers
import tensorflow as tf
from matplotlib.pyplot import specgram
import glob

In [129]:
y_test_new

     audio_filenames     Label
0       E_0000000024     spoof
1       E_0000000034     spoof
2       E_0000000076     spoof
3       E_0000000111     spoof
4       E_0000000146     spoof
...              ...       ...
6995    E_0000106133     spoof
6996    E_0000106138  bonafide
6997    E_0000106142  bonafide
6998    E_0000106158     spoof
6999    E_0000106161     spoof

[7000 rows x 2 columns]

In [10]:
from sklearn.metrics import confusion_matrix
import IPython.display as ipd  # To play sound in the notebook
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras
import sys
import warnings
# ignore warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)
import json

from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')

import pickle
import joblib
from tensorflow.keras import models, layers
import tensorflow as tf

In [18]:
import tensorflow as tf

# Simple operation
with tf.device('/GPU:0'):
    a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
    b = tf.constant([[1.0, 1.0], [0.0, 1.0]])
    c = tf.matmul(a, b)

print(c)

# Check where the tensor was placed
print("Operation executed on:", c.device)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
Operation executed on: /job:localhost/replica:0/task:0/device:GPU:0

In [12]:
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available: 1

In [8]:
import tensorflow as tf
import librosa
import os

In [26]:
pip install ffmpeg

Defaulting to user installation because normal site-packages is not writeable
Collecting ffmpeg
  Downloading ffmpeg-1.4.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ffmpeg
  Building wheel for ffmpeg (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6082 sha256=9a34e0c2d141d532efe8a2a5039eaa8d21fb51146cc3f7feca77e7875c09df23
  Stored in directory: /umbc/rs/iharp/users/zkhanja1/.cache/pip/wheels/56/30/c5/576bdd729f3bc062d62a551be7fefd6ed2f761901568171e4e
Successfully built ffmpeg
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!module load FFmpeg/7.0.2-GCCcore-13.3.0

In [14]:
import ffmpeg

ModuleNotFoundError: No module named 'ffmpeg'

In [ ]:
!ffmpeg -version

In [15]:
import os
import subprocess
#flac_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train'
#wav_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train_converted_wav'

In [ ]:
!pip install ffmpeg-python

import ffmpeg
import os

#flac_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train'
#wav_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train_converted_wav'

os.makedirs(wav_folder, exist_ok=True)

for file in os.listdir(flac_folder):
    if file.endswith(".flac"):
        flac_path = os.path.join(flac_folder, file)
        wav_path = os.path.join(wav_folder, file.replace(".flac", ".wav"))
        
        # Convert .flac to .wav using ffmpeg-python
        ffmpeg.input(flac_path).output(wav_path).run()

In [20]:
import numpy as np
from sklearn.metrics import roc_curve

def compute_eer(y_true, y_probs):
    """
    Computes the Equal Error Rate (EER) as the average of FPR and FNR.
    
    Parameters:
        y_true (array-like): True binary labels (0 or 1).
        y_probs (array-like): Predicted probabilities for the positive class.

    Returns:
        eer (float): Equal Error Rate (average of FPR and FNR).
        eer_threshold (float): Threshold where FPR and FNR are closest.
    """
    # Compute ROC curve
    fpr, tpr, thresholds = roc_curve(y_true, y_probs)

    # Compute False Negative Rate (FNR)
    fnr = 1 - tpr  # FNR = 1 - TPR

    # Find the threshold where FPR and FNR are closest
    eer_index = np.nanargmin(np.abs(fpr - fnr))  # Get index of min difference
    eer_threshold = thresholds[eer_index]

    # Compute EER as the average of FPR and FNR at that threshold
    eer = (fpr[eer_index] + fnr[eer_index]) / 2

    return eer, eer_threshold

In [110]:

eer, eer_threshold = compute_eer(y_train, probs_train)
print(f"EER (Average of FPR & FNR): {eer:.4f}, Threshold: {eer_threshold:.4f}")

EER (Average of FPR & FNR): 0.0040, Threshold: 0.9067

In [111]:
from sklearn.metrics import confusion_matrix
import numpy as np

def compute_eer_fixed_threshold(y_true, y_scores, threshold):
    """
    Compute the Equal Error Rate (EER) at a fixed threshold.
    
    Parameters:
    - y_true: array-like of shape (n_samples,) -> True binary labels (0 or 1)
    - y_scores: array-like of shape (n_samples,) -> Predicted scores/probabilities
    - threshold: float, the fixed threshold at which to compute EER
    
    Returns:
    - eer: float, the average of FPR and FNR at the fixed threshold
    """
    # Convert scores to binary predictions using the fixed threshold
    y_pred = (y_scores >= threshold).astype(int)
    
    # Compute confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
    # Compute False Positive Rate (FPR) and False Negative Rate (FNR)
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0
    
    # Compute EER as the average of FPR and FNR
    eer = (fpr + fnr) / 2
    
    return eer

In [112]:
eer_test = compute_eer_fixed_threshold(y_test, probs_test, 0.9067)

In [113]:
eer_test

np.float64(0.4924250886190909)

In [ ]:
/umbc/rs/iharp/users/zkhanja1/converted_wavs_df_7000

In [20]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

Fake vs real Detection using HuBERT:

In [115]:
y_test1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_xlsr_df_flac_E_eval_asvspoof5_0to5000.xlsx')

In [120]:
y_train1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_xlsr_df_flac_T_aa_asvspoof5_0to7000.xlsx')

In [117]:
y_test2= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_xlsr_df_flac_E_eval_asvspoof5_5000to10000.xlsx')

In [24]:
#y_train2= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_HuBERT_df_T_3001to7000.xlsx')

In [121]:
y_test = pd.concat([y_test1, y_test2], ignore_index=True)

In [122]:
y_train = y_train1

In [123]:
y_test = y_test.iloc[:7000,:]

In [124]:
y_test

        audio_filenames
0     E_0000000024.flac
1     E_0000000034.flac
2     E_0000000076.flac
3     E_0000000111.flac
4     E_0000000146.flac
...                 ...
6995  E_0000106133.flac
6996  E_0000106138.flac
6997  E_0000106142.flac
6998  E_0000106158.flac
6999  E_0000106161.flac

[7000 rows x 1 columns]

In [125]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac
7000  T_0000007000.flac

[7001 rows x 1 columns]

In [ ]:
 #Df_train_with_labels.csv

In [ ]:
 #Df_eval_all_parts_with_labels.csv

In [126]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

In [127]:
Df_train_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/asvspoof5/protocols/ASVspoof5.train.tsv', sep=' ', header=None)

In [128]:
Df_train_with_labels

                        0  1  2  3  4    5         6         7  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [129]:
Df_train_with_labels.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [130]:
 Df_eval_all_parts_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/asvspoof5/protocols/ASVspoof5.eval.track_1.tsv', sep=' ', header=None)

In [131]:
Df_eval_all_parts_with_labels

,0,1,2,3,4,5,6,7,8,9
0,E_1607,E_0009538969,M,C05,2,E_0009486171,AC1,A26,spoof,-
1,E_3614,E_0009249178,F,C11,4,E_0006756001,AC1,A27,spoof,-
2,E_2192,E_0004993854,F,-,0,-,-,bonafide,bonafide,-
3,E_0237,E_0006624752,M,C01,1,E_0007675046,AC2,A25,spoof,-
4,E_0884,E_0007708293,F,C07,5,E_0006994972,AC1,A21,spoof,-
...,...,...,...,...,...,...,...,...,...,...
680769,E_1010,E_0008087696,F,C04,5,E_0007677371,AC2,A18,spoof,-
680770,E_0153,E_0000166820,F,C05,5,E_0003527674,AC2,A20,spoof,-
680771,E_2066,E_0005788355,F,C10,1,E_0005111271,-,bonafide,bonafide,-
680772,E_3642,E_0006926359,F,C03,4,E_0009054133,AC1,A25,spoof,-
680773,E_1707,E_0005792079,M,-,0,-,AC2,A24,spoof,-

In [132]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac
7000  T_0000007000.flac

[7001 rows x 1 columns]

In [133]:

#y_train['audio_filenames'] = y_train['audio_filenames'].str.replace('.flac', '', regex=False)

# 2. Rename 'FileName' column to 'audio_filenames' in Df_train_with_labels
Df_train_with_labels = Df_train_with_labels.rename(columns={0: 'audio_filenames'})
Df_train_with_labels = Df_train_with_labels.rename(columns={7: 'Label'})

In [134]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac
7000  T_0000007000.flac

[7001 rows x 1 columns]

In [135]:
Df_train_with_labels

          audio_filenames  1  2  3  4    5         6     Label  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [89]:
#Df_train_with_labels['audio_filenames'] = Df_train_with_labels['audio_filenames'].str.replace('.flac', '', regex=False)

In [136]:
Df_train_with_labels

          audio_filenames  1  2  3  4    5         6     Label  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [90]:
Df_train_with_labels

       audio_filenames  1  2  3  4    5         6     Label  8
0         T_0000000000  F  -  -  -  AC3       A05     spoof  -
1         T_0000000001  M  -  -  -  AC3       A07     spoof  -
2         T_0000000002  M  -  -  -  AC2       A04     spoof  -
3         T_0000000003  M  -  -  -  AC2       A08     spoof  -
4         T_0000000004  M  -  -  -  AC2       A05     spoof  -
...                ... .. .. .. ..  ...       ...       ... ..
182352    T_0000182352  F  -  -  -  AC2       A03     spoof  -
182353    T_0000182353  M  -  -  -  AC2       A05     spoof  -
182354    T_0000182354  M  -  -  -  AC3       A02     spoof  -
182355    T_0000182355  M  -  -  -    -  bonafide  bonafide  -
182356    T_0000182356  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [138]:
# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_train_new = y_train.merge(Df_train_with_labels[['audio_filenames', 'Label']], 
                            on='audio_filenames', 
                            how='left')

In [139]:
y_train_new

        audio_filenames     Label
0     T_0000000000.flac     spoof
1     T_0000000001.flac     spoof
2     T_0000000002.flac     spoof
3     T_0000000003.flac     spoof
4     T_0000000004.flac     spoof
...                 ...       ...
6996  T_0000006996.flac     spoof
6997  T_0000006997.flac     spoof
6998  T_0000006998.flac  bonafide
6999  T_0000006999.flac     spoof
7000  T_0000007000.flac     spoof

[7001 rows x 2 columns]

In [140]:
null_count = y_train_new['Label'].isnull().sum()

print(f"Number of missing 'Label' values in y_train_new: {null_count}")

Number of missing 'Label' values in y_train_new: 0

In [141]:
y_test

        audio_filenames
0     E_0000000024.flac
1     E_0000000034.flac
2     E_0000000076.flac
3     E_0000000111.flac
4     E_0000000146.flac
...                 ...
6995  E_0000106133.flac
6996  E_0000106138.flac
6997  E_0000106142.flac
6998  E_0000106158.flac
6999  E_0000106161.flac

[7000 rows x 1 columns]

In [142]:
Df_eval_all_parts_with_labels

,0,1,2,3,4,5,6,7,8,9
0,E_1607,E_0009538969,M,C05,2,E_0009486171,AC1,A26,spoof,-
1,E_3614,E_0009249178,F,C11,4,E_0006756001,AC1,A27,spoof,-
2,E_2192,E_0004993854,F,-,0,-,-,bonafide,bonafide,-
3,E_0237,E_0006624752,M,C01,1,E_0007675046,AC2,A25,spoof,-
4,E_0884,E_0007708293,F,C07,5,E_0006994972,AC1,A21,spoof,-
...,...,...,...,...,...,...,...,...,...,...
680769,E_1010,E_0008087696,F,C04,5,E_0007677371,AC2,A18,spoof,-
680770,E_0153,E_0000166820,F,C05,5,E_0003527674,AC2,A20,spoof,-
680771,E_2066,E_0005788355,F,C10,1,E_0005111271,-,bonafide,bonafide,-
680772,E_3642,E_0006926359,F,C03,4,E_0009054133,AC1,A25,spoof,-
680773,E_1707,E_0005792079,M,-,0,-,AC2,A24,spoof,-

In [143]:
y_test['audio_filenames'] = y_test['audio_filenames'].str.replace('.flac', '', regex=False)

In [ ]:
#Df_eval_all_parts_with_labels['audio_filenames'] = Df_eval_all_parts_with_labels['audio_filenames'].str.replace('.flac', '', regex=False)

In [144]:
Df_eval_all_parts_with_labels

,0,1,2,3,4,5,6,7,8,9
0,E_1607,E_0009538969,M,C05,2,E_0009486171,AC1,A26,spoof,-
1,E_3614,E_0009249178,F,C11,4,E_0006756001,AC1,A27,spoof,-
2,E_2192,E_0004993854,F,-,0,-,-,bonafide,bonafide,-
3,E_0237,E_0006624752,M,C01,1,E_0007675046,AC2,A25,spoof,-
4,E_0884,E_0007708293,F,C07,5,E_0006994972,AC1,A21,spoof,-
...,...,...,...,...,...,...,...,...,...,...
680769,E_1010,E_0008087696,F,C04,5,E_0007677371,AC2,A18,spoof,-
680770,E_0153,E_0000166820,F,C05,5,E_0003527674,AC2,A20,spoof,-
680771,E_2066,E_0005788355,F,C10,1,E_0005111271,-,bonafide,bonafide,-
680772,E_3642,E_0006926359,F,C03,4,E_0009054133,AC1,A25,spoof,-
680773,E_1707,E_0005792079,M,-,0,-,AC2,A24,spoof,-

In [145]:



# 2. Rename 'FileName' column to 'audio_filenames' in Df_train_with_labels
Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={1: 'audio_filenames'})
Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={8: 'Label'})

In [146]:
Df_eval_all_parts_with_labels

,0,audio_filenames,2,3,4,5,6,7,Label,9
0,E_1607,E_0009538969,M,C05,2,E_0009486171,AC1,A26,spoof,-
1,E_3614,E_0009249178,F,C11,4,E_0006756001,AC1,A27,spoof,-
2,E_2192,E_0004993854,F,-,0,-,-,bonafide,bonafide,-
3,E_0237,E_0006624752,M,C01,1,E_0007675046,AC2,A25,spoof,-
4,E_0884,E_0007708293,F,C07,5,E_0006994972,AC1,A21,spoof,-
...,...,...,...,...,...,...,...,...,...,...
680769,E_1010,E_0008087696,F,C04,5,E_0007677371,AC2,A18,spoof,-
680770,E_0153,E_0000166820,F,C05,5,E_0003527674,AC2,A20,spoof,-
680771,E_2066,E_0005788355,F,C10,1,E_0005111271,-,bonafide,bonafide,-
680772,E_3642,E_0006926359,F,C03,4,E_0009054133,AC1,A25,spoof,-
680773,E_1707,E_0005792079,M,-,0,-,AC2,A24,spoof,-

In [147]:
y_test

     audio_filenames
0       E_0000000024
1       E_0000000034
2       E_0000000076
3       E_0000000111
4       E_0000000146
...              ...
6995    E_0000106133
6996    E_0000106138
6997    E_0000106142
6998    E_0000106158
6999    E_0000106161

[7000 rows x 1 columns]

In [148]:
# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_test_new = y_test.merge(Df_eval_all_parts_with_labels[['audio_filenames', 'Label']], 
                            on='audio_filenames', 
                            how='left')

In [149]:
y_test_new

     audio_filenames     Label
0       E_0000000024     spoof
1       E_0000000034     spoof
2       E_0000000076     spoof
3       E_0000000111     spoof
4       E_0000000146     spoof
...              ...       ...
6995    E_0000106133     spoof
6996    E_0000106138  bonafide
6997    E_0000106142  bonafide
6998    E_0000106158     spoof
6999    E_0000106161     spoof

[7000 rows x 2 columns]

In [150]:
# Check for null values in the 'Label' column
null_count = y_test_new['Label'].isnull().sum()

print(f"Number of missing 'Label' values in y_test_new: {null_count}")

Number of missing 'Label' values in y_test_new: 0

In [11]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

In [151]:
y_train_new.to_csv('asvspoof5_DF_labels_corresponding_to_xlsr_7000_train.csv')

In [152]:
y_test_new.to_csv('asvspoof5_DF_labels_corresponding_to_xlsr_7000_test.csv')

In [9]:
y_train = pd.read_csv('asvspoof5_DF_labels_corresponding_to_xlsr_7000_train.csv')

In [10]:
y_test = pd.read_csv('asvspoof5_DF_labels_corresponding_to_xlsr_7000_test.csv')

In [11]:
len(y_test)

7000

In [12]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

In [13]:

X_test1 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/xlsr_hidden_states_df_flac_E_eval_asvspoof5_0to5000.npy')
X_test2 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/xlsr_hidden_states_df_flac_E_eval_asvspoof5_5000to10000.npy')
#X_test3 = np.load('/umbc/rs/iharp/users/zkhanja1/npy_files/HuBERT_hidden_states_df_eval_7000_4000to7000.npy')

# Concatenate them in order
X_test = np.concatenate((X_test1, X_test2), axis=0)

# Save X_test to a new .npy file if needed
# np.save('X_test.npy', X_test)

In [14]:
print(f"Shape of X_test: {X_test.shape}")

Shape of X_test: (10000, 549, 1024)

In [15]:
X_test2 = X_test[:7000]

In [16]:
X_test2.shape

(7000, 549, 1024)

In [17]:
X_test = X_test2

In [18]:
import numpy as np

# Load the .npy files for X_train
X_train1 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/xlsr_hidden_states_df_flac_T_aa_asvspoof5_0to7000.npy')
#X_train2 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/HuBERT_hidden_states_df_T_3001to7000.npy')
#X_train3 = np.load('/umbc/rs/iharp/users/zkhanja1/npy_files/HuBERT_hidden_states_df_train_7000_4000to7000.npy')

# Concatenate them in order


# Print the shape of X_train
#print(f"Shape of X_train: {X_train.shape}")

In [19]:
X_train = X_train1

In [20]:
print(f"Shape of X_train: {X_train.shape}")

Shape of X_train: (7001, 549, 1024)

In [21]:
y_train

      Unnamed: 0    audio_filenames     Label
0              0  T_0000000000.flac     spoof
1              1  T_0000000001.flac     spoof
2              2  T_0000000002.flac     spoof
3              3  T_0000000003.flac     spoof
4              4  T_0000000004.flac     spoof
...          ...                ...       ...
6996        6996  T_0000006996.flac     spoof
6997        6997  T_0000006997.flac     spoof
6998        6998  T_0000006998.flac  bonafide
6999        6999  T_0000006999.flac     spoof
7000        7000  T_0000007000.flac     spoof

[7001 rows x 3 columns]

In [22]:
y_train_new = y_train
y_test_new = y_test

In [23]:
# For y_train_new
y_train = y_train_new['Label'].map({'spoof': 1, 'bonafide': 0})
print(f"First few y_train values:\n{y_train.head()}")

First few y_train values:
0    1
1    1
2    1
3    1
4    1
Name: Label, dtype: int64

In [24]:
# For y_test_new
y_test = y_test_new['Label'].map({'spoof': 1, 'bonafide': 0})
print(f"First few y_test values:\n{y_test.head()}")

First few y_test values:
0    1
1    1
2    1
3    1
4    1
Name: Label, dtype: int64

In [25]:
# Calculate the percentage of 1s in y_train
percentage_1_train = (y_train == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_train: {percentage_1_train:.2f}%")

# Calculate the percentage of 1s in y_test
percentage_1_test = (y_test == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_test: {percentage_1_test:.2f}%")

Percentage of '1' (spoof) in y_train: 89.36%
Percentage of '1' (spoof) in y_test: 79.16%

In [81]:
!pip install --upgrade scikit-learn
!pip install --upgrade imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imbalanced-learn in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (0.11.0)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.13.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy<3,>=1.24.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy<2,>=1.10.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.15.2)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.6.1)
Collecting sklearn-compat<1,>=0.1 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: joblib<2,>=1.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.13.0-py3-none-any.whl (238 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.4/238.4 kB 5.4 MB/s eta 0:00:00:00:01
Downloading sklearn_compat-0.1.3-py3-none-any.whl (18 kB)
Installing collected packages: sklearn-compat, imbalanced-learn
Successfully installed imbalanced-learn-0.13.0 sklearn-compat-0.1.3

In [26]:
y_train

0       1
1       1
2       1
3       1
4       1
       ..
6996    1
6997    1
6998    0
6999    1
7000    1
Name: Label, Length: 7001, dtype: int64

In [27]:
from imblearn.over_sampling import SMOTE

# First, ensure y_train is a numpy array if it's not already
y_train_np = y_train.values if hasattr(y_train, 'values') else y_train

# Apply SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train.reshape(X_train.shape[0], -1), y_train_np)

# If needed, reshape X_train_resampled back to original dimensions
X_train_resampled = X_train_resampled.reshape(-1, X_train.shape[1], X_train.shape[2])

# Print new class distribution
print(f"Resampled class distribution:\n{pd.Series(y_train_resampled).value_counts()}")

Resampled class distribution:
1    6256
0    6256
Name: count, dtype: int64

In [30]:
print(f"Resampled class distribution:\n{pd.Series(y_train_resampled).value_counts()}")

Resampled class distribution:
1    6256
0    6256
Name: count, dtype: int64

In [31]:
from tensorflow.keras.metrics import AUC

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam

# Flatten input shape for MLP
input_dim = X_train_resampled.shape[1] * X_train_resampled.shape[2]

model = Sequential([
    Flatten(input_shape=(X_train_resampled.shape[1], X_train_resampled.shape[2])),
    Dense(128, activation='relu'),
   # Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.6),
    Dense(1, activation='sigmoid')
])



model.compile(
    optimizer=Adam(learning_rate=0.001), 
    loss='binary_crossentropy', 
    metrics=[AUC(name='roc_auc')]
)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1762739388.253309 3542700 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43490 MB memory:  -> device: 0, name: NVIDIA L40S, pci bus id: 0000:49:00.0, compute capability: 8.9

In [34]:
X_train_resampled.shape

(12512, 549, 1024)

In [35]:
#X_train_resampled = np.squeeze(X_train_resampled, axis=1)
#X_train = np.squeeze(X_train, axis=1)
#X_test= np.squeeze(X_test, axis=1)

In [37]:
from tensorflow.keras.callbacks import EarlyStopping

# Define early stopping
early_stop = EarlyStopping(
    monitor='val_roc_auc',   # monitor validation AUC
    patience=5,              # stop if no improvement after 5 epochs
    mode='max',              # maximize AUC
    restore_best_weights=True  # restore the best model weights
)

In [38]:
history = model.fit(
    X_train_resampled, y_train_resampled,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/50

2025-11-09 21:01:42.107156: I external/local_xla/xla/service/service.cc:163] XLA service 0x1550fc018e10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2025-11-09 21:01:42.107174: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA L40S, Compute Capability 8.9
2025-11-09 21:01:43.596720: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2025-11-09 21:01:45.087471: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91301
2025-11-09 21:01:45.931862: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-09 21:01:45.932060: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-09 21:01:45.932106: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-09 21:01:45.932132: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 116 configs for 5 fusions on a single thread.
2025-11-09 21:01:48.907919: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_149', 100 bytes spill stores, 100 bytes spill loads

2025-11-09 21:01:53.537386: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_743', 520 bytes spill stores, 520 bytes spill loads

2025-11-09 21:01:55.599453: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_745', 8 bytes spill stores, 8 bytes spill loads

2025-11-09 21:01:56.458882: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_745', 132 bytes spill stores, 132 bytes spill loads

2025-11-09 21:01:56.914162: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_745', 468 bytes spill stores, 468 bytes spill loads

 11/333 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - loss: 7.2161 - roc_auc: 0.5366

I0000 00:00:1762740121.276437 3545317 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

329/333 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 2.4468 - roc_auc: 0.5039

2025-11-09 21:02:06.811202: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 27 configs for 5 fusions on a single thread.

333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.4317 - roc_auc: 0.5038

2025-11-09 21:02:12.766380: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-09 21:02:12.766641: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 41 configs for 2 fusions on a single thread.
2025-11-09 21:02:14.374917: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_48', 292 bytes spill stores, 292 bytes spill loads

333/333 ━━━━━━━━━━━━━━━━━━━━ 36s 47ms/step - loss: 1.1845 - roc_auc: 0.4981 - val_loss: 0.8212 - val_roc_auc: 0.0000e+00
Epoch 2/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 13s 20ms/step - loss: 0.6844 - roc_auc: 0.5016 - val_loss: 0.8300 - val_roc_auc: 0.0000e+00
Epoch 3/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - loss: 0.6806 - roc_auc: 0.4902 - val_loss: 0.8401 - val_roc_auc: 0.0000e+00
Epoch 4/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - loss: 0.6805 - roc_auc: 0.5103 - val_loss: 0.9102 - val_roc_auc: 0.0000e+00
Epoch 5/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - loss: 0.6779 - roc_auc: 0.4968 - val_loss: 0.8605 - val_roc_auc: 0.0000e+00
Epoch 6/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - loss: 0.6777 - roc_auc: 0.4927 - val_loss: 0.8750 - val_roc_auc: 0.0000e+00

In [39]:
# Get probabilities for original X_train and X_test
probs_train = model.predict(X_train)
probs_test = model.predict(X_test)

print(f"First 5 probabilities on X_train:\n{probs_train[:5].flatten()}")
print(f"First 5 probabilities on X_test:\n{probs_test[:5].flatten()}")

215/219 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2025-11-09 21:03:24.787397: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-09 21:03:24.787600: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 41 configs for 2 fusions on a single thread.
2025-11-09 21:03:26.380140: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_17', 292 bytes spill stores, 292 bytes spill loads

219/219 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step
215/219 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2025-11-09 21:03:40.632048: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-09 21:03:40.632240: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 41 configs for 2 fusions on a single thread.
2025-11-09 21:03:42.218959: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_17', 292 bytes spill stores, 292 bytes spill loads

219/219 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step
First 5 probabilities on X_train:
[0.56160504 0.5606657  0.5617816  0.5614011  0.5588395 ]
First 5 probabilities on X_test:
[0.5598093  0.56002206 0.5596106  0.5607086  0.5613245 ]

In [40]:
len(X_test)

7000

In [41]:
y_test

0       1
1       1
2       1
3       1
4       1
       ..
6995    1
6996    0
6997    0
6998    1
6999    1
Name: Label, Length: 7000, dtype: int64

In [42]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on training data: 0.6020
ROC AUC on test data: 0.5349

In [43]:
probs_test

array([[0.5598093 ],
       [0.56002206],
       [0.5596106 ],
       ...,
       [0.5609844 ],
       [0.55974925],
       [0.56205064]], shape=(7000, 1), dtype=float32)

In [44]:
unique_values = np.unique(probs_test)
print(unique_values)

[0.5565081  0.55671465 0.55703896 ... 0.5654048  0.56545866 0.5657598 ]

In [45]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

0

In [46]:
# Assuming X_train shape is (samples, time_steps, features)
X_train_resampled = np.expand_dims(X_train_resampled, axis=1)  # (samples, 1, time_steps, features)
#X_val = np.expand_dims(X_val, axis=1)
X_train = np.expand_dims(X_train, axis=1)
X_test = np.expand_dims(X_test, axis=1)

In [47]:
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

def build_resnet18(input_shape):
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2D(64, 7, strides=2, padding='same', use_bias=False)(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D(3, strides=2, padding='same')(x)

    def residual_block(x, filters, downsample=False):
        shortcut = x
        strides = 2 if downsample else 1
        x = layers.Conv2D(filters, 3, strides=strides, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)
        x = layers.ReLU()(x)
        x = layers.Conv2D(filters, 3, strides=1, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)

        if downsample or shortcut.shape[-1] != filters:
            shortcut = layers.Conv2D(filters, 1, strides=strides, padding='same', use_bias=False,
                                     kernel_regularizer=regularizers.l2(1e-4))(shortcut)
            shortcut = layers.BatchNormalization()(shortcut)

        x = layers.add([x, shortcut])
        x = layers.ReLU()(x)
        return x

    x = residual_block(x, 64)
    x = residual_block(x, 64)
    x = residual_block(x, 128, downsample=True)
    x = residual_block(x, 128)
    x = residual_block(x, 256, downsample=True)
    x = residual_block(x, 256)
    x = residual_block(x, 512, downsample=True)
    x = residual_block(x, 512)

    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(1, activation='sigmoid')(x)

    model = models.Model(inputs, outputs)
    return model

input_shape = X_train_resampled.shape[1:]  # (time_steps, features, 1)
resnet18_model = build_resnet18(input_shape)

In [48]:
from tensorflow.keras.optimizers import Adam

resnet18_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=[tf.keras.metrics.AUC(name='roc_auc')]
)

In [49]:
history = resnet18_model.fit(
    X_train_resampled, y_train_resampled,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 48s 57ms/step - loss: 0.3943 - roc_auc: 0.9869 - val_loss: 0.2745 - val_roc_auc: 0.0000e+00
Epoch 2/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 46s 22ms/step - loss: 0.1954 - roc_auc: 0.9995 - val_loss: 0.1865 - val_roc_auc: 0.0000e+00
Epoch 3/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - loss: 0.1869 - roc_auc: 0.9997 - val_loss: 0.1703 - val_roc_auc: 0.0000e+00
Epoch 4/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - loss: 0.1818 - roc_auc: 0.9995 - val_loss: 26.5075 - val_roc_auc: 0.0000e+00
Epoch 5/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 11s 25ms/step - loss: 0.1654 - roc_auc: 1.0000 - val_loss: 0.2752 - val_roc_auc: 0.0000e+00

In [50]:
probs_train = resnet18_model.predict(X_train).flatten()
probs_test = resnet18_model.predict(X_test).flatten()

print(f"First 5 probabilities (train): {probs_train[:5]}")
print(f"First 5 probabilities (test): {probs_test[:5]}")

219/219 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step
219/219 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
First 5 probabilities (train): [0.04404461 0.17671645 0.09361901 0.13088901 0.145528  ]
First 5 probabilities (test): [0.31590167 0.11647809 0.21840838 0.4947934  0.17608564]

In [79]:
y_test = y_test[:7000]

In [90]:
X_test.shape

(7000, 1, 549, 768)

In [51]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

ROC AUC on training data: 0.8969

In [52]:
probs_test = resnet18_model.predict(X_test).flatten()

219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step

In [53]:
len(probs_test)

7000

In [54]:

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on test data: 0.6706

In [55]:
df_train_preds = pd.DataFrame({
    'audio_filenames': y_train_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_train.flatten()
})

In [56]:
df_train_preds

        audio_filenames  prob_spoof
0     T_0000000000.flac    0.044045
1     T_0000000001.flac    0.176716
2     T_0000000002.flac    0.093619
3     T_0000000003.flac    0.130889
4     T_0000000004.flac    0.145528
...                 ...         ...
6996  T_0000006996.flac    0.195978
6997  T_0000006997.flac    0.020163
6998  T_0000006998.flac    0.047112
6999  T_0000006999.flac    0.244248
7000  T_0000007000.flac    0.055482

[7001 rows x 2 columns]

In [57]:
# Save train predictions
df_train_preds.to_csv('asvspoof5_train_predictions_xlsr_resnet18_7000_df.csv', index=False)

In [58]:
len(y_test_new)

7000

In [59]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

6987

In [60]:
# Create DataFrame for test predictions
df_test_preds = pd.DataFrame({
    'audio_filenames': y_test_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_test.flatten()
})

In [61]:
df_test_preds

     audio_filenames  prob_spoof
0       E_0000000024    0.315902
1       E_0000000034    0.116478
2       E_0000000076    0.218408
3       E_0000000111    0.494793
4       E_0000000146    0.176086
...              ...         ...
6995    E_0000106133    0.113229
6996    E_0000106138    0.213950
6997    E_0000106142    0.197099
6998    E_0000106158    0.166105
6999    E_0000106161    0.315822

[7000 rows x 2 columns]

In [62]:
# Save test predictions
df_test_preds.to_csv('asvspoof5_test_predictions_xlsr_resnet18_7000_df.csv', index=False)

In [63]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'