# HuBERT - ASVspoof 5

In [1]:
import pandas as pd

In [2]:
import tensorflow as tf

In [ ]:
#import torch

In [40]:
pd

In [6]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy<2,>=1.21 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install -U scikit-learn scipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: scipy in /home/zkhanja1/.local/lib/python3.11/site-packages (1.15.2)
Collecting scipy
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 58.2 MB/s eta 0:00:00:00:0100:01
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
Successfully installed scipy-1.15.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install librosa

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: librosa in /home/zkhanja1/.local/lib/python3.11/site-packages (0.11.0)
Requirement already satisfied: audioread>=2.1.9 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (3.0.1)
Requirement already satisfied: numba>=0.51.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.59.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.15.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.2.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (5.1.1)
Requirement already satisfied: soundfile>=0.12.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.5.0.post1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (4.9.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.3)
Requirement already satisfied: msgpack>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.0.3)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.51.0->librosa) (0.42.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (3.10.0)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (23.1)
Requirement already satisfied: requests>=2.19.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (2.31.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from soundfile>=0.12.1->librosa) (1.16.0)
Requirement already satisfied: pycparser in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2024.2.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install resampy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: resampy in /home/zkhanja1/.local/lib/python3.11/site-packages (0.4.3)
Requirement already satisfied: numpy>=1.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (1.26.4)
Requirement already satisfied: numba>=0.53 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (0.59.0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.53->resampy) (0.42.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install tf_slim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tf_slim in /home/zkhanja1/.local/lib/python3.11/site-packages (1.1.0)
Requirement already satisfied: absl-py>=0.2.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from tf_slim) (2.2.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from tensorflow.keras.models import Model
from tensorflow.keras import Input
from tensorflow.keras.layers import concatenate, Permute, Reshape
import os

In [4]:
import math
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential

In [5]:
#from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LSTM,TimeDistributed
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [6]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import BatchNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy as np
import sklearn.metrics as metrics

In [7]:
import pandas as pd
import math
import numpy as np
#from numpy.lib.function_base import average
import os
import librosa
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras import models, layers
import tensorflow as tf
from matplotlib.pyplot import specgram
import glob

In [129]:
y_test_new

     audio_filenames     Label
0       E_0000000024     spoof
1       E_0000000034     spoof
2       E_0000000076     spoof
3       E_0000000111     spoof
4       E_0000000146     spoof
...              ...       ...
6995    E_0000106133     spoof
6996    E_0000106138  bonafide
6997    E_0000106142  bonafide
6998    E_0000106158     spoof
6999    E_0000106161     spoof

[7000 rows x 2 columns]

In [8]:
from sklearn.metrics import confusion_matrix
import IPython.display as ipd  # To play sound in the notebook
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras
import sys
import warnings
# ignore warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)
import json

from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')

import pickle
import joblib
from tensorflow.keras import models, layers
import tensorflow as tf

In [18]:
import tensorflow as tf

# Simple operation
with tf.device('/GPU:0'):
    a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
    b = tf.constant([[1.0, 1.0], [0.0, 1.0]])
    c = tf.matmul(a, b)

print(c)

# Check where the tensor was placed
print("Operation executed on:", c.device)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
Operation executed on: /job:localhost/replica:0/task:0/device:GPU:0

In [12]:
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available: 1

In [19]:
import tensorflow as tf
import librosa
import os

In [26]:
pip install ffmpeg

Defaulting to user installation because normal site-packages is not writeable
Collecting ffmpeg
  Downloading ffmpeg-1.4.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ffmpeg
  Building wheel for ffmpeg (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6082 sha256=9a34e0c2d141d532efe8a2a5039eaa8d21fb51146cc3f7feca77e7875c09df23
  Stored in directory: /umbc/rs/iharp/users/zkhanja1/.cache/pip/wheels/56/30/c5/576bdd729f3bc062d62a551be7fefd6ed2f761901568171e4e
Successfully built ffmpeg
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!module load FFmpeg/7.0.2-GCCcore-13.3.0

In [14]:
import ffmpeg

ModuleNotFoundError: No module named 'ffmpeg'

In [ ]:
!ffmpeg -version

In [15]:
import os
import subprocess
#flac_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train'
#wav_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train_converted_wav'

In [ ]:
!pip install ffmpeg-python

import ffmpeg
import os

#flac_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train'
#wav_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train_converted_wav'

os.makedirs(wav_folder, exist_ok=True)

for file in os.listdir(flac_folder):
    if file.endswith(".flac"):
        flac_path = os.path.join(flac_folder, file)
        wav_path = os.path.join(wav_folder, file.replace(".flac", ".wav"))
        
        # Convert .flac to .wav using ffmpeg-python
        ffmpeg.input(flac_path).output(wav_path).run()

In [9]:
import numpy as np
from sklearn.metrics import roc_curve

def compute_eer(y_true, y_probs):
    """
    Computes the Equal Error Rate (EER) as the average of FPR and FNR.
    
    Parameters:
        y_true (array-like): True binary labels (0 or 1).
        y_probs (array-like): Predicted probabilities for the positive class.

    Returns:
        eer (float): Equal Error Rate (average of FPR and FNR).
        eer_threshold (float): Threshold where FPR and FNR are closest.
    """
    # Compute ROC curve
    fpr, tpr, thresholds = roc_curve(y_true, y_probs)

    # Compute False Negative Rate (FNR)
    fnr = 1 - tpr  # FNR = 1 - TPR

    # Find the threshold where FPR and FNR are closest
    eer_index = np.nanargmin(np.abs(fpr - fnr))  # Get index of min difference
    eer_threshold = thresholds[eer_index]

    # Compute EER as the average of FPR and FNR at that threshold
    eer = (fpr[eer_index] + fnr[eer_index]) / 2

    return eer, eer_threshold

In [17]:

eer, eer_threshold = compute_eer(y_train, probs_train)
print(f"EER (Average of FPR & FNR): {eer:.4f}, Threshold: {eer_threshold:.4f}")

NameError: name 'y_train' is not defined

In [10]:
from sklearn.metrics import confusion_matrix
import numpy as np

def compute_eer_fixed_threshold(y_true, y_scores, threshold):
    """
    Compute the Equal Error Rate (EER) at a fixed threshold.
    
    Parameters:
    - y_true: array-like of shape (n_samples,) -> True binary labels (0 or 1)
    - y_scores: array-like of shape (n_samples,) -> Predicted scores/probabilities
    - threshold: float, the fixed threshold at which to compute EER
    
    Returns:
    - eer: float, the average of FPR and FNR at the fixed threshold
    """
    # Convert scores to binary predictions using the fixed threshold
    y_pred = (y_scores >= threshold).astype(int)
    
    # Compute confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
    # Compute False Positive Rate (FPR) and False Negative Rate (FNR)
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0
    
    # Compute EER as the average of FPR and FNR
    eer = (fpr + fnr) / 2
    
    return eer

In [85]:
eer_test = compute_eer_fixed_threshold(y_test, probs_test, 0.6189)

In [86]:
eer_test

0.1719582454743819

In [ ]:
/umbc/rs/iharp/users/zkhanja1/converted_wavs_df_7000

In [20]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

Fake vs real Detection using HuBERT:

In [21]:
y_test1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_HuBERT_df_eval_1to5000.xlsx')

In [23]:
y_train1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_HuBERT_df_T_0to3000.xlsx')

In [22]:
y_test2= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_HuBERT_df_eval_5000to10000.xlsx')

In [24]:
y_train2= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_HuBERT_df_T_3001to7000.xlsx')

In [25]:
y_test = pd.concat([y_test1, y_test2], ignore_index=True)

In [26]:
y_train = pd.concat([y_train1, y_train2], ignore_index=True)

In [29]:
y_test = y_test.iloc[:7000,:]

In [30]:
y_test

        audio_filenames
0     E_0000000024.flac
1     E_0000000034.flac
2     E_0000000076.flac
3     E_0000000111.flac
4     E_0000000146.flac
...                 ...
6995  E_0000106133.flac
6996  E_0000106138.flac
6997  E_0000106142.flac
6998  E_0000106158.flac
6999  E_0000106161.flac

[7000 rows x 1 columns]

In [28]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6995  T_0000006995.flac
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac

[7000 rows x 1 columns]

In [ ]:
 #Df_train_with_labels.csv

In [ ]:
 #Df_eval_all_parts_with_labels.csv

In [31]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

In [80]:
Df_train_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/asvspoof5/protocols/ASVspoof5.train.tsv', sep=' ', header=None)

In [81]:
Df_train_with_labels

                        0  1  2  3  4    5         6         7  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [82]:
Df_train_with_labels.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [96]:
 Df_eval_all_parts_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/asvspoof5/protocols/ASVspoof5.eval.track_1.tsv', sep=' ', header=None)

In [97]:
Df_eval_all_parts_with_labels

,0,1,2,3,4,5,6,7,8,9
0,E_1607,E_0009538969,M,C05,2,E_0009486171,AC1,A26,spoof,-
1,E_3614,E_0009249178,F,C11,4,E_0006756001,AC1,A27,spoof,-
2,E_2192,E_0004993854,F,-,0,-,-,bonafide,bonafide,-
3,E_0237,E_0006624752,M,C01,1,E_0007675046,AC2,A25,spoof,-
4,E_0884,E_0007708293,F,C07,5,E_0006994972,AC1,A21,spoof,-
...,...,...,...,...,...,...,...,...,...,...
680769,E_1010,E_0008087696,F,C04,5,E_0007677371,AC2,A18,spoof,-
680770,E_0153,E_0000166820,F,C05,5,E_0003527674,AC2,A20,spoof,-
680771,E_2066,E_0005788355,F,C10,1,E_0005111271,-,bonafide,bonafide,-
680772,E_3642,E_0006926359,F,C03,4,E_0009054133,AC1,A25,spoof,-
680773,E_1707,E_0005792079,M,-,0,-,AC2,A24,spoof,-

In [47]:
y_train

     audio_filenames
0       T_0000000000
1       T_0000000001
2       T_0000000002
3       T_0000000003
4       T_0000000004
...              ...
6995    T_0000006995
6996    T_0000006996
6997    T_0000006997
6998    T_0000006998
6999    T_0000006999

[7000 rows x 1 columns]

In [87]:

#y_train['audio_filenames'] = y_train['audio_filenames'].str.replace('.flac', '', regex=False)

# 2. Rename 'FileName' column to 'audio_filenames' in Df_train_with_labels
Df_train_with_labels = Df_train_with_labels.rename(columns={0: 'audio_filenames'})
Df_train_with_labels = Df_train_with_labels.rename(columns={7: 'Label'})

In [41]:
y_train

0       1
1       1
2       1
3       1
4       1
       ..
6995    1
6996    1
6997    1
6998    0
6999    1
Name: Label, Length: 7000, dtype: int64

In [88]:
Df_train_with_labels

          audio_filenames  1  2  3  4    5         6     Label  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [89]:
Df_train_with_labels['audio_filenames'] = Df_train_with_labels['audio_filenames'].str.replace('.flac', '', regex=False)

In [104]:
Df_train_with_labels

       audio_filenames  1  2  3  4    5         6     Label  8
0         T_0000000000  F  -  -  -  AC3       A05     spoof  -
1         T_0000000001  M  -  -  -  AC3       A07     spoof  -
2         T_0000000002  M  -  -  -  AC2       A04     spoof  -
3         T_0000000003  M  -  -  -  AC2       A08     spoof  -
4         T_0000000004  M  -  -  -  AC2       A05     spoof  -
...                ... .. .. .. ..  ...       ...       ... ..
182352    T_0000182352  F  -  -  -  AC2       A03     spoof  -
182353    T_0000182353  M  -  -  -  AC2       A05     spoof  -
182354    T_0000182354  M  -  -  -  AC3       A02     spoof  -
182355    T_0000182355  M  -  -  -    -  bonafide  bonafide  -
182356    T_0000182356  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [106]:
Df_eval_all_parts_with_labels['audio_filenames'] = Df_eval_all_parts_with_labels['audio_filenames'].str.replace('.flac', '', regex=False)

In [90]:
Df_train_with_labels

       audio_filenames  1  2  3  4    5         6     Label  8
0         T_0000000000  F  -  -  -  AC3       A05     spoof  -
1         T_0000000001  M  -  -  -  AC3       A07     spoof  -
2         T_0000000002  M  -  -  -  AC2       A04     spoof  -
3         T_0000000003  M  -  -  -  AC2       A08     spoof  -
4         T_0000000004  M  -  -  -  AC2       A05     spoof  -
...                ... .. .. .. ..  ...       ...       ... ..
182352    T_0000182352  F  -  -  -  AC2       A03     spoof  -
182353    T_0000182353  M  -  -  -  AC2       A05     spoof  -
182354    T_0000182354  M  -  -  -  AC3       A02     spoof  -
182355    T_0000182355  M  -  -  -    -  bonafide  bonafide  -
182356    T_0000182356  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [91]:
# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_train_new = y_train.merge(Df_train_with_labels[['audio_filenames', 'Label']], 
                            on='audio_filenames', 
                            how='left')

In [92]:
y_train_new

     audio_filenames     Label
0       T_0000000000     spoof
1       T_0000000001     spoof
2       T_0000000002     spoof
3       T_0000000003     spoof
4       T_0000000004     spoof
...              ...       ...
6995    T_0000006995     spoof
6996    T_0000006996     spoof
6997    T_0000006997     spoof
6998    T_0000006998  bonafide
6999    T_0000006999     spoof

[7000 rows x 2 columns]

In [93]:
null_count = y_train_new['Label'].isnull().sum()

print(f"Number of missing 'Label' values in y_train_new: {null_count}")

Number of missing 'Label' values in y_train_new: 0

In [101]:
y_test

        audio_filenames
0     E_0000000024.flac
1     E_0000000034.flac
2     E_0000000076.flac
3     E_0000000111.flac
4     E_0000000146.flac
...                 ...
6995  E_0000106133.flac
6996  E_0000106138.flac
6997  E_0000106142.flac
6998  E_0000106158.flac
6999  E_0000106161.flac

[7000 rows x 1 columns]

In [98]:
Df_eval_all_parts_with_labels

,0,1,2,3,4,5,6,7,8,9
0,E_1607,E_0009538969,M,C05,2,E_0009486171,AC1,A26,spoof,-
1,E_3614,E_0009249178,F,C11,4,E_0006756001,AC1,A27,spoof,-
2,E_2192,E_0004993854,F,-,0,-,-,bonafide,bonafide,-
3,E_0237,E_0006624752,M,C01,1,E_0007675046,AC2,A25,spoof,-
4,E_0884,E_0007708293,F,C07,5,E_0006994972,AC1,A21,spoof,-
...,...,...,...,...,...,...,...,...,...,...
680769,E_1010,E_0008087696,F,C04,5,E_0007677371,AC2,A18,spoof,-
680770,E_0153,E_0000166820,F,C05,5,E_0003527674,AC2,A20,spoof,-
680771,E_2066,E_0005788355,F,C10,1,E_0005111271,-,bonafide,bonafide,-
680772,E_3642,E_0006926359,F,C03,4,E_0009054133,AC1,A25,spoof,-
680773,E_1707,E_0005792079,M,-,0,-,AC2,A24,spoof,-

In [111]:
y_test['audio_filenames'] = y_test['audio_filenames'].str.replace('.flac', '', regex=False)

In [99]:



# 2. Rename 'FileName' column to 'audio_filenames' in Df_train_with_labels
Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={1: 'audio_filenames'})
Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={8: 'Label'})

In [105]:
Df_eval_all_parts_with_labels

,0,audio_filenames,2,3,4,5,6,7,Label,9
0,E_1607,E_0009538969,M,C05,2,E_0009486171,AC1,A26,spoof,-
1,E_3614,E_0009249178,F,C11,4,E_0006756001,AC1,A27,spoof,-
2,E_2192,E_0004993854,F,-,0,-,-,bonafide,bonafide,-
3,E_0237,E_0006624752,M,C01,1,E_0007675046,AC2,A25,spoof,-
4,E_0884,E_0007708293,F,C07,5,E_0006994972,AC1,A21,spoof,-
...,...,...,...,...,...,...,...,...,...,...
680769,E_1010,E_0008087696,F,C04,5,E_0007677371,AC2,A18,spoof,-
680770,E_0153,E_0000166820,F,C05,5,E_0003527674,AC2,A20,spoof,-
680771,E_2066,E_0005788355,F,C10,1,E_0005111271,-,bonafide,bonafide,-
680772,E_3642,E_0006926359,F,C03,4,E_0009054133,AC1,A25,spoof,-
680773,E_1707,E_0005792079,M,-,0,-,AC2,A24,spoof,-

In [110]:
y_test

        audio_filenames
0     E_0000000024.flac
1     E_0000000034.flac
2     E_0000000076.flac
3     E_0000000111.flac
4     E_0000000146.flac
...                 ...
6995  E_0000106133.flac
6996  E_0000106138.flac
6997  E_0000106142.flac
6998  E_0000106158.flac
6999  E_0000106161.flac

[7000 rows x 1 columns]

In [112]:
# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_test_new = y_test.merge(Df_eval_all_parts_with_labels[['audio_filenames', 'Label']], 
                            on='audio_filenames', 
                            how='left')

In [113]:
y_test_new

     audio_filenames     Label
0       E_0000000024     spoof
1       E_0000000034     spoof
2       E_0000000076     spoof
3       E_0000000111     spoof
4       E_0000000146     spoof
...              ...       ...
6995    E_0000106133     spoof
6996    E_0000106138  bonafide
6997    E_0000106142  bonafide
6998    E_0000106158     spoof
6999    E_0000106161     spoof

[7000 rows x 2 columns]

In [114]:
# Check for null values in the 'Label' column
null_count = y_test_new['Label'].isnull().sum()

print(f"Number of missing 'Label' values in y_test_new: {null_count}")

Number of missing 'Label' values in y_test_new: 0

In [11]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

In [115]:
y_train_new.to_csv('asvspoof5_DF_labels_corresponding_to_hubert_7000_train.csv')

In [116]:
y_test_new.to_csv('asvspoof5_DF_labels_corresponding_to_hubert_7000_test.csv')

In [11]:
y_train = pd.read_csv('asvspoof5_DF_labels_corresponding_to_hubert_7000_train.csv')

In [12]:
y_test = pd.read_csv('asvspoof5_DF_labels_corresponding_to_hubert_7000_test.csv')

In [13]:
len(y_test)

7000

In [52]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

In [14]:

X_test1 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/HuBERT_hidden_states_df_eval_1to5000.npy')
X_test2 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/HuBERT_hidden_states_df_eval_5000to10000.npy')
#X_test3 = np.load('/umbc/rs/iharp/users/zkhanja1/npy_files/HuBERT_hidden_states_df_eval_7000_4000to7000.npy')

# Concatenate them in order
X_test = np.concatenate((X_test1, X_test2), axis=0)

# Save X_test to a new .npy file if needed
# np.save('X_test.npy', X_test)

In [15]:
print(f"Shape of X_test: {X_test.shape}")

Shape of X_test: (10000, 549, 768)

In [16]:
X_test2 = X_test[:7000]

In [17]:
X_test2.shape

(7000, 549, 768)

In [18]:
import numpy as np

# Load the .npy files for X_train
X_train1 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/HuBERT_hidden_states_df_T_0to3000.npy')
X_train2 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/HuBERT_hidden_states_df_T_3001to7000.npy')
#X_train3 = np.load('/umbc/rs/iharp/users/zkhanja1/npy_files/HuBERT_hidden_states_df_train_7000_4000to7000.npy')

# Concatenate them in order


# Print the shape of X_train
#print(f"Shape of X_train: {X_train.shape}")

In [19]:
X_train = np.concatenate((X_train1, X_train2), axis=0)

In [20]:
print(f"Shape of X_train: {X_train.shape}")

Shape of X_train: (7000, 549, 768)

In [21]:
y_train

      Unnamed: 0 audio_filenames     Label
0              0    T_0000000000     spoof
1              1    T_0000000001     spoof
2              2    T_0000000002     spoof
3              3    T_0000000003     spoof
4              4    T_0000000004     spoof
...          ...             ...       ...
6995        6995    T_0000006995     spoof
6996        6996    T_0000006996     spoof
6997        6997    T_0000006997     spoof
6998        6998    T_0000006998  bonafide
6999        6999    T_0000006999     spoof

[7000 rows x 3 columns]

In [22]:
y_train_new = y_train
y_test_new = y_test

In [23]:
# For y_train_new
y_train = y_train_new['Label'].map({'spoof': 1, 'bonafide': 0})
print(f"First few y_train values:\n{y_train.head()}")

First few y_train values:
0    1
1    1
2    1
3    1
4    1
Name: Label, dtype: int64

In [24]:
# For y_test_new
y_test = y_test_new['Label'].map({'spoof': 1, 'bonafide': 0})
print(f"First few y_test values:\n{y_test.head()}")

First few y_test values:
0    1
1    1
2    1
3    1
4    1
Name: Label, dtype: int64

In [25]:
# Calculate the percentage of 1s in y_train
percentage_1_train = (y_train == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_train: {percentage_1_train:.2f}%")

# Calculate the percentage of 1s in y_test
percentage_1_test = (y_test == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_test: {percentage_1_test:.2f}%")

Percentage of '1' (spoof) in y_train: 89.36%
Percentage of '1' (spoof) in y_test: 79.16%

In [81]:
!pip install --upgrade scikit-learn
!pip install --upgrade imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imbalanced-learn in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (0.11.0)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.13.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy<3,>=1.24.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy<2,>=1.10.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.15.2)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.6.1)
Collecting sklearn-compat<1,>=0.1 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: joblib<2,>=1.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.13.0-py3-none-any.whl (238 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.4/238.4 kB 5.4 MB/s eta 0:00:00:00:01
Downloading sklearn_compat-0.1.3-py3-none-any.whl (18 kB)
Installing collected packages: sklearn-compat, imbalanced-learn
Successfully installed imbalanced-learn-0.13.0 sklearn-compat-0.1.3

In [26]:
from imblearn.over_sampling import SMOTE

# First, ensure y_train is a numpy array if it's not already
y_train_np = y_train.values if hasattr(y_train, 'values') else y_train

# Apply SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train.reshape(X_train.shape[0], -1), y_train_np)

# If needed, reshape X_train_resampled back to original dimensions
X_train_resampled = X_train_resampled.reshape(-1, X_train.shape[1], X_train.shape[2])

# Print new class distribution
print(f"Resampled class distribution:\n{pd.Series(y_train_resampled).value_counts()}")

Resampled class distribution:
1    6255
0    6255
Name: count, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

# Use 10% of the original X_train and y_train as validation
#X_train_sub, X_val, y_train_sub, y_val = train_test_split(
#    X_train, y_train, test_size=0.1, random_state=42, stratify=y_train
#)

In [27]:
from tensorflow.keras.metrics import AUC

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam

# Flatten input shape for MLP
input_dim = X_train_resampled.shape[1] * X_train_resampled.shape[2]

model = Sequential([
    Flatten(input_shape=(X_train_resampled.shape[1], X_train_resampled.shape[2])),
    Dense(128, activation='relu'),
   # Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.6),
    Dense(1, activation='sigmoid')
])



model.compile(
    optimizer=Adam(learning_rate=0.001), 
    loss='binary_crossentropy', 
    metrics=[AUC(name='roc_auc')]
)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1763485975.811683 1431565 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43490 MB memory:  -> device: 0, name: NVIDIA L40S, pci bus id: 0000:c9:00.0, compute capability: 8.9

In [97]:
X_train_resampled.shape

(12510, 549, 768)

In [99]:
#X_train_resampled = np.squeeze(X_train_resampled, axis=1)
X_train = np.squeeze(X_train, axis=1)
X_test= np.squeeze(X_test, axis=1)

In [98]:
history = model.fit(
    X_train_resampled, y_train_resampled,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/50

2025-11-08 11:21:36.077996: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-08 11:21:36.078528: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-08 11:21:36.078571: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-08 11:21:36.078598: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 116 configs for 5 fusions on a single thread.
2025-11-08 11:21:37.681435: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_149', 100 bytes spill stores, 100 bytes spill loads

2025-11-08 11:21:42.326062: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_743', 520 bytes spill stores, 520 bytes spill loads

2025-11-08 11:21:44.400301: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_745', 8 bytes spill stores, 8 bytes spill loads

2025-11-08 11:21:45.266911: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_745', 132 bytes spill stores, 132 bytes spill loads

2025-11-08 11:21:45.724043: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_745', 468 bytes spill stores, 468 bytes spill loads

332/333 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.6297 - roc_auc: 0.9227

2025-11-08 11:22:00.404873: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 27 configs for 5 fusions on a single thread.

333/333 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6286 - roc_auc: 0.9229

2025-11-08 11:22:06.662981: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-08 11:22:06.663326: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 41 configs for 2 fusions on a single thread.
2025-11-08 11:22:08.257786: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_48', 292 bytes spill stores, 292 bytes spill loads

333/333 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - loss: 0.2714 - roc_auc: 0.9752 - val_loss: 0.0069 - val_roc_auc: 0.0000e+00
Epoch 2/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 12s 20ms/step - loss: 0.0275 - roc_auc: 0.9988 - val_loss: 0.0074 - val_roc_auc: 0.0000e+00
Epoch 3/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 0.0149 - roc_auc: 0.9992 - val_loss: 1.3845e-05 - val_roc_auc: 0.0000e+00
Epoch 4/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 17ms/step - loss: 0.0336 - roc_auc: 0.9976 - val_loss: 1.1876e-05 - val_roc_auc: 0.0000e+00
Epoch 5/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 0.0103 - roc_auc: 0.9995 - val_loss: 2.8569e-05 - val_roc_auc: 0.0000e+00

In [100]:
# Get probabilities for original X_train and X_test
probs_train = model.predict(X_train)
probs_test = model.predict(X_test)

print(f"First 5 probabilities on X_train:\n{probs_train[:5].flatten()}")
print(f"First 5 probabilities on X_test:\n{probs_test[:5].flatten()}")

215/219 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2025-11-08 11:24:21.530211: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-08 11:24:21.530431: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 41 configs for 2 fusions on a single thread.
2025-11-08 11:24:23.116090: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_17', 292 bytes spill stores, 292 bytes spill loads

219/219 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step
First 5 probabilities on X_train:
[1.         1.         0.99999475 0.99999905 0.9999999 ]
First 5 probabilities on X_test:
[1. 1. 1. 1. 1.]

In [41]:
len(X_test)

6998

In [40]:
y_test

0       1
1       1
2       1
3       1
4       1
       ..
6994    1
6995    1
6996    1
6997    1
6998    1
Name: Label, Length: 6999, dtype: int64

In [101]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on training data: 0.9999
ROC AUC on test data: 0.5221

In [58]:
probs_test

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [59]:
unique_values = np.unique(probs_test)
print(unique_values)

[1.11031072e-17 2.00934760e-17 2.14623806e-17 4.43134749e-17
 5.05572129e-17 7.02908769e-17 1.31468513e-16 1.35873270e-16
 1.71125524e-16 1.82784456e-16 2.15523934e-16 4.30567388e-16
 7.05856801e-16 7.79204931e-16 8.32292933e-16 1.89700059e-15
 2.68126839e-15 3.72783054e-15 5.09819856e-15 6.11127156e-15
 6.21281684e-15 6.74631588e-15 9.07552943e-15 9.85488953e-15
 1.01850689e-14 1.16200952e-14 1.28276042e-14 1.72563939e-14
 2.13784170e-14 2.39920592e-14 2.64851092e-14 3.22754281e-14
 3.86888634e-14 3.93316463e-14 4.71472328e-14 5.20464680e-14
 6.03662086e-14 9.11360966e-14 1.12905690e-13 1.22601243e-13
 1.94472436e-13 2.04327305e-13 2.14681585e-13 4.89311282e-13
 7.03095243e-13 7.50997842e-13 1.02706808e-12 1.15262921e-12
 1.17177915e-12 1.25160873e-12 1.31503142e-12 1.71170901e-12
 1.76905181e-12 1.85869484e-12 1.88958267e-12 2.41936809e-12
 2.67077332e-12 3.30874542e-12 3.36371079e-12 4.30682486e-12
 4.91364371e-12 5.51434679e-12 5.79377475e-12 5.89002241e-12
 6.61010136e-12 6.76369421e-12 7.66675525e-12 8.60403155e-12
 8.89228535e-12 9.49810716e-12 1.11994060e-11 1.21611532e-11
 1.38746540e-11 1.43394576e-11 1.48198901e-11 1.48285412e-11
 1.53164183e-11 1.77647463e-11 2.46987899e-11 2.51090902e-11
 2.86469477e-11 2.91228881e-11 3.37782441e-11 3.85375030e-11
 4.11629481e-11 4.39674130e-11 4.61952837e-11 4.85361334e-11
 5.01623014e-11 5.27040737e-11 6.52935761e-11 7.09005146e-11
 7.57308868e-11 8.36003697e-11 1.43995982e-10 1.48820442e-10
 1.53806259e-10 1.69788822e-10 2.17393631e-10 2.32203978e-10
 2.43970899e-10 2.52144472e-10 2.64920863e-10 3.07269044e-10
 3.12374626e-10 3.17563809e-10 3.22839255e-10 3.28203548e-10
 3.39198475e-10 3.68327091e-10 4.06601308e-10 4.79431606e-10
 5.03725839e-10 5.56069801e-10 5.74700454e-10 6.24051644e-10
 6.44958753e-10 6.77640721e-10 7.21226467e-10 7.48056839e-10
 8.12296119e-10 8.38445757e-10 8.82050266e-10 1.28847966e-09
 1.59625779e-09 1.91345362e-09 2.40990294e-09 2.44994136e-09
 2.61684785e-09 2.93676838e-09 3.03515657e-09 3.32429906e-09
 3.35055117e-09 3.40621731e-09 3.57882035e-09 3.63827901e-09
 3.76016951e-09 4.92095742e-09 6.04262684e-09 1.14024212e-08
 1.60439928e-08 1.75678565e-08 3.61749386e-08 3.64234261e-08
 3.74495492e-08 4.07192324e-08 4.20982644e-08 4.22731183e-08
 4.47675816e-08 4.60144562e-08 5.19466568e-08 5.20670831e-08
 7.69944961e-08 1.04878495e-07 1.12655862e-07 1.19746105e-07
 2.43198116e-07 3.06885767e-07 3.31506953e-07 3.50007610e-07
 6.30586328e-07 8.52353537e-07 8.71388977e-07 9.65923959e-07
 1.22670986e-06 2.43145314e-06 2.87746138e-06 3.53684891e-06
 3.79142330e-06 5.30005991e-06 1.10021174e-05 1.28825068e-05
 1.71441407e-05 2.46290583e-05 2.75309376e-05 5.23512717e-05
 5.84526388e-05 5.89124647e-05 6.08146693e-05 8.28350239e-05
 8.36295949e-05 9.63739658e-05 1.04346982e-04 1.05793122e-04
 1.10904155e-04 1.18482189e-04 1.20084485e-04 1.26263694e-04
 1.27616833e-04 1.44743361e-04 2.22390270e-04 2.40236433e-04
 3.04730347e-04 3.68531997e-04 4.95069718e-04 6.12986565e-04
 6.24429551e-04 8.08415178e-04 8.90317140e-04 1.18275185e-03
 1.26494782e-03 1.45422632e-03 1.76866062e-03 2.42890161e-03
 2.98068835e-03 3.30089848e-03 4.23149113e-03 4.37520444e-03
 5.17069083e-03 5.25547797e-03 7.25933677e-03 7.78580178e-03
 7.81377405e-03 7.96654634e-03 8.41393974e-03 8.59746709e-03
 8.66804458e-03 9.85148456e-03 1.02110831e-02 1.20752510e-02
 1.20810661e-02 1.29451565e-02 1.32084759e-02 1.49156172e-02
 1.60416607e-02 1.66978668e-02 1.69647411e-02 1.70290582e-02
 1.88513435e-02 1.89143457e-02 2.01280732e-02 2.03846581e-02
 2.21624244e-02 2.34067291e-02 2.44516693e-02 2.66416837e-02
 2.70943940e-02 3.28009166e-02 4.00415882e-02 4.11027670e-02
 4.29294296e-02 4.96554971e-02 5.01117967e-02 5.22098802e-02
 5.56058027e-02 5.58568873e-02 5.86716384e-02 5.91450743e-02
 5.96049912e-02 6.10633157e-02 6.18660375e-02 6.21044785e-02
 6.23555109e-02 6.42025918e-02 6.45648092e-02 6.52926713e-02
 6.54272065e-02 6.61016852e-02 6.66174442e-02 6.71637580e-02
 6.74839839e-02 7.12887645e-02 7.13771954e-02 7.13962168e-02
 7.40214884e-02 7.46818185e-02 7.55632073e-02 7.62739331e-02
 7.72374272e-02 7.82877803e-02 7.83247799e-02 7.89871588e-02
 8.10869262e-02 8.10930878e-02 8.55037794e-02 8.77040103e-02
 8.84992406e-02 9.19975415e-02 9.53662470e-02 9.85710248e-02
 1.08506605e-01 1.14102677e-01 1.31337985e-01 1.44934207e-01
 1.62213251e-01 1.72214925e-01 1.75664261e-01 1.90198183e-01
 1.90385982e-01 1.99049175e-01 2.01939747e-01 2.94180632e-01
 3.40423763e-01 3.49381238e-01 3.75998795e-01 3.79417747e-01
 3.87744009e-01 4.19562072e-01 4.38980758e-01 4.78286505e-01
 5.01563430e-01 5.75188279e-01 6.10121906e-01 6.24641240e-01
 6.32822692e-01 6.43747807e-01 6.52251422e-01 6.74947798e-01
 7.00505137e-01 7.07642436e-01 7.23681867e-01 7.84746706e-01
 7.94607401e-01 7.97875106e-01 8.36382627e-01 8.47266257e-01
 8.85246634e-01 8.95809352e-01 9.12426353e-01 9.13586199e-01
 9.20096874e-01 9.24338460e-01 9.28384423e-01 9.41657901e-01
 9.58073497e-01 9.58560467e-01 9.65800941e-01 9.70418692e-01
 9.71064985e-01 9.71152544e-01 9.71931636e-01 9.77896333e-01
 9.80897069e-01 9.81195927e-01 9.84153211e-01 9.84827042e-01
 9.85842049e-01 9.91280854e-01 9.92953956e-01 9.94866371e-01
 9.94963586e-01 9.95188236e-01 9.95419562e-01 9.95928824e-01
 9.96048033e-01 9.96498466e-01 9.96513724e-01 9.96556222e-01
 9.97184217e-01 9.97402966e-01 9.97493386e-01 9.98035610e-01
 9.98141766e-01 9.98256624e-01 9.98280168e-01 9.98342752e-01
 9.98379707e-01 9.98461366e-01 9.98755813e-01 9.98857260e-01
 9.99016285e-01 9.99238729e-01 9.99240637e-01 9.99267995e-01
 9.99286056e-01 9.99458969e-01 9.99543130e-01 9.99615788e-01
 9.99712050e-01 9.99736130e-01 9.99746382e-01 9.99875665e-01
 9.99893785e-01 9.99906421e-01 9.99922395e-01 9.99943733e-01
 9.99945641e-01 9.99956250e-01 9.99957800e-01 9.99960780e-01
 9.99962926e-01 9.99963403e-01 9.99965072e-01 9.99965549e-01
 9.99985814e-01 9.99986768e-01 9.99992132e-01 9.99992371e-01
 9.99995112e-01 9.99995351e-01 9.99995828e-01 9.99995947e-01
 9.99996543e-01 9.99997616e-01 9.99997735e-01 9.99998450e-01
 9.99998569e-01 9.99999046e-01 9.99999166e-01 9.99999285e-01
 9.99999404e-01 9.99999523e-01 9.99999762e-01 9.99999881e-01
 1.00000000e+00]

In [61]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

307

In [30]:
# Assuming X_train shape is (samples, time_steps, features)
X_train_resampled = np.expand_dims(X_train_resampled, axis=1)  # (samples, 1, time_steps, features)
#X_val = np.expand_dims(X_val, axis=1)
X_train = np.expand_dims(X_train, axis=1)
X_test = np.expand_dims(X_test, axis=1)

In [31]:
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

def build_resnet18(input_shape):
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2D(64, 7, strides=2, padding='same', use_bias=False)(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D(3, strides=2, padding='same')(x)

    def residual_block(x, filters, downsample=False):
        shortcut = x
        strides = 2 if downsample else 1
        x = layers.Conv2D(filters, 3, strides=strides, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)
        x = layers.ReLU()(x)
        x = layers.Conv2D(filters, 3, strides=1, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)

        if downsample or shortcut.shape[-1] != filters:
            shortcut = layers.Conv2D(filters, 1, strides=strides, padding='same', use_bias=False,
                                     kernel_regularizer=regularizers.l2(1e-4))(shortcut)
            shortcut = layers.BatchNormalization()(shortcut)

        x = layers.add([x, shortcut])
        x = layers.ReLU()(x)
        return x

    x = residual_block(x, 64)
    x = residual_block(x, 64)
    x = residual_block(x, 128, downsample=True)
    x = residual_block(x, 128)
    x = residual_block(x, 256, downsample=True)
    x = residual_block(x, 256)
    x = residual_block(x, 512, downsample=True)
    x = residual_block(x, 512)

    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(1, activation='sigmoid')(x)

    model = models.Model(inputs, outputs)
    return model

input_shape = X_train_resampled.shape[1:]  # (time_steps, features, 1)
resnet18_model = build_resnet18(input_shape)

In [46]:
from tensorflow.keras.optimizers import Adam

resnet18_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=[tf.keras.metrics.AUC(name='roc_auc')]
)

In [47]:
from tensorflow.keras.callbacks import EarlyStopping

# Define early stopping
early_stop = EarlyStopping(
    monitor='val_roc_auc',   # monitor validation AUC
    patience=5,              # stop if no improvement after 5 epochs
    mode='max',              # maximize AUC
    restore_best_weights=True  # restore the best model weights
)

In [48]:
history = resnet18_model.fit(
    X_train_resampled, y_train_resampled,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - loss: 0.1929 - roc_auc: 0.9993 - val_loss: 0.1759 - val_roc_auc: 0.0000e+00
Epoch 2/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 26s 21ms/step - loss: 0.1719 - roc_auc: 0.9999 - val_loss: 0.1678 - val_roc_auc: 0.0000e+00
Epoch 3/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - loss: 0.1610 - roc_auc: 1.0000 - val_loss: 0.1648 - val_roc_auc: 0.0000e+00
Epoch 4/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - loss: 0.1539 - roc_auc: 0.9999 - val_loss: 0.1675 - val_roc_auc: 0.0000e+00
Epoch 5/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - loss: 0.1431 - roc_auc: 1.0000 - val_loss: 0.1368 - val_roc_auc: 0.0000e+00
Epoch 6/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 11s 22ms/step - loss: 0.1322 - roc_auc: 1.0000 - val_loss: 0.1266 - val_roc_auc: 0.0000e+00

In [61]:
probs_train = resnet18_model.predict(X_train)
probs_test = resnet18_model.predict(X_test)

print(f"First 5 probabilities (train): {probs_train[:5]}")
print(f"First 5 probabilities (test): {probs_test[:5]}")

219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step
First 5 probabilities (train): [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
First 5 probabilities (test): [[3.4369950e-03]
 [9.1524583e-01]
 [3.3080518e-02]
 [9.7701681e-01]
 [7.9269358e-04]]

In [37]:
y_test.shape

(7000,)

In [63]:
probs_train

array([[1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       ...,
       [1.0000000e+00],
       [1.0591374e-06],
       [1.0000000e+00]], shape=(7000, 1), dtype=float32)

In [79]:
#y_test = y_test[:7000]

In [50]:
X_test_2 = X_test[:7000]

In [51]:
X_test_2.shape

(7000, 1, 549, 768)

In [52]:
X_test = X_test_2

In [64]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

ROC AUC on training data: 1.0000

In [65]:
#probs_test = resnet18_model.predict(X_test).flatten()

In [66]:
len(probs_test)

7000

In [56]:

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on test data: 0.6654

In [68]:
df_train_preds = pd.DataFrame({
    'audio_filenames': y_train_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_train.flatten()
})

In [69]:
df_train_preds

     audio_filenames  prob_spoof
0       T_0000000000    1.000000
1       T_0000000001    1.000000
2       T_0000000002    1.000000
3       T_0000000003    1.000000
4       T_0000000004    1.000000
...              ...         ...
6995    T_0000006995    1.000000
6996    T_0000006996    1.000000
6997    T_0000006997    1.000000
6998    T_0000006998    0.000001
6999    T_0000006999    1.000000

[7000 rows x 2 columns]

In [70]:
# Save train predictions
df_train_preds.to_csv('asvspoof5_train_predictions_hubert_resnet18_7000_df.csv', index=False)

In [71]:
len(y_test_new)

7000

In [72]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

1880

In [73]:
# Create DataFrame for test predictions
df_test_preds = pd.DataFrame({
    'audio_filenames': y_test_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_test.flatten()
})

In [74]:
df_test_preds

     audio_filenames  prob_spoof
0       E_0000000024    0.003437
1       E_0000000034    0.915246
2       E_0000000076    0.033081
3       E_0000000111    0.977017
4       E_0000000146    0.000793
...              ...         ...
6995    E_0000106133    0.015859
6996    E_0000106138    0.995039
6997    E_0000106142    0.999999
6998    E_0000106158    0.005510
6999    E_0000106161    0.222590

[7000 rows x 2 columns]

In [75]:
# Save test predictions
df_test_preds.to_csv('asvspoof5_test_predictions_hubert_resnet18_7000_df.csv', index=False)