# XLSR - ITW

In [5]:
import pandas as pd

In [6]:
import tensorflow as tf

In [3]:
#import torch

In [37]:
pd

In [6]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy<2,>=1.21 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install -U scikit-learn scipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: scipy in /home/zkhanja1/.local/lib/python3.11/site-packages (1.15.2)
Collecting scipy
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 58.2 MB/s eta 0:00:00:00:0100:01
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
Successfully installed scipy-1.15.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install librosa

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: librosa in /home/zkhanja1/.local/lib/python3.11/site-packages (0.11.0)
Requirement already satisfied: audioread>=2.1.9 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (3.0.1)
Requirement already satisfied: numba>=0.51.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.59.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.15.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.2.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (5.1.1)
Requirement already satisfied: soundfile>=0.12.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.5.0.post1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (4.9.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.3)
Requirement already satisfied: msgpack>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.0.3)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.51.0->librosa) (0.42.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (3.10.0)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (23.1)
Requirement already satisfied: requests>=2.19.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (2.31.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from soundfile>=0.12.1->librosa) (1.16.0)
Requirement already satisfied: pycparser in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2024.2.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install resampy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: resampy in /home/zkhanja1/.local/lib/python3.11/site-packages (0.4.3)
Requirement already satisfied: numpy>=1.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (1.26.4)
Requirement already satisfied: numba>=0.53 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (0.59.0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.53->resampy) (0.42.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install tf_slim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tf_slim in /home/zkhanja1/.local/lib/python3.11/site-packages (1.1.0)
Requirement already satisfied: absl-py>=0.2.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from tf_slim) (2.2.2)
Note: you may need to restart the kernel to use updated packages.

In [8]:
from tensorflow.keras.models import Model
from tensorflow.keras import Input
from tensorflow.keras.layers import concatenate, Permute, Reshape
import os

In [9]:
import math
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential

In [10]:
#from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LSTM,TimeDistributed
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [11]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import BatchNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy as np
import sklearn.metrics as metrics

In [12]:
import pandas as pd
import math
import numpy as np
#from numpy.lib.function_base import average
import os
import librosa
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras import models, layers
import tensorflow as tf
from matplotlib.pyplot import specgram
import glob

In [129]:
y_test_new

     audio_filenames     Label
0       E_0000000024     spoof
1       E_0000000034     spoof
2       E_0000000076     spoof
3       E_0000000111     spoof
4       E_0000000146     spoof
...              ...       ...
6995    E_0000106133     spoof
6996    E_0000106138  bonafide
6997    E_0000106142  bonafide
6998    E_0000106158     spoof
6999    E_0000106161     spoof

[7000 rows x 2 columns]

In [13]:
from sklearn.metrics import confusion_matrix
import IPython.display as ipd  # To play sound in the notebook
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras
import sys
import warnings
# ignore warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)
import json

from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')

import pickle
import joblib
from tensorflow.keras import models, layers
import tensorflow as tf

In [11]:
import tensorflow as tf

# Simple operation
with tf.device('/GPU:0'):
    a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
    b = tf.constant([[1.0, 1.0], [0.0, 1.0]])
    c = tf.matmul(a, b)

print(c)

# Check where the tensor was placed
print("Operation executed on:", c.device)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1767888310.865805 2015047 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22804 MB memory:  -> device: 0, name: Quadro RTX 6000, pci bus id: 0000:1b:00.0, compute capability: 7.5

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
Operation executed on: /job:localhost/replica:0/task:0/device:GPU:0

In [12]:
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available: 1

In [14]:
import tensorflow as tf
import librosa
import os

In [26]:
pip install ffmpeg

Defaulting to user installation because normal site-packages is not writeable
Collecting ffmpeg
  Downloading ffmpeg-1.4.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ffmpeg
  Building wheel for ffmpeg (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6082 sha256=9a34e0c2d141d532efe8a2a5039eaa8d21fb51146cc3f7feca77e7875c09df23
  Stored in directory: /umbc/rs/iharp/users/zkhanja1/.cache/pip/wheels/56/30/c5/576bdd729f3bc062d62a551be7fefd6ed2f761901568171e4e
Successfully built ffmpeg
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!module load FFmpeg/7.0.2-GCCcore-13.3.0

In [14]:
import ffmpeg

ModuleNotFoundError: No module named 'ffmpeg'

In [ ]:
!ffmpeg -version

In [15]:
import os
import subprocess
#flac_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train'
#wav_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train_converted_wav'

In [ ]:
!pip install ffmpeg-python

import ffmpeg
import os

#flac_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train'
#wav_folder = '/umbc/rs/vjaneja/users/zkhanja1/first_7000_subset_pa_train_converted_wav'

os.makedirs(wav_folder, exist_ok=True)

for file in os.listdir(flac_folder):
    if file.endswith(".flac"):
        flac_path = os.path.join(flac_folder, file)
        wav_path = os.path.join(wav_folder, file.replace(".flac", ".wav"))
        
        # Convert .flac to .wav using ffmpeg-python
        ffmpeg.input(flac_path).output(wav_path).run()

In [15]:
import numpy as np
from sklearn.metrics import roc_curve

def compute_eer(y_true, y_probs):
    """
    Computes the Equal Error Rate (EER) as the average of FPR and FNR.
    
    Parameters:
        y_true (array-like): True binary labels (0 or 1).
        y_probs (array-like): Predicted probabilities for the positive class.

    Returns:
        eer (float): Equal Error Rate (average of FPR and FNR).
        eer_threshold (float): Threshold where FPR and FNR are closest.
    """
    # Compute ROC curve
    fpr, tpr, thresholds = roc_curve(y_true, y_probs)

    # Compute False Negative Rate (FNR)
    fnr = 1 - tpr  # FNR = 1 - TPR

    # Find the threshold where FPR and FNR are closest
    eer_index = np.nanargmin(np.abs(fpr - fnr))  # Get index of min difference
    eer_threshold = thresholds[eer_index]

    # Compute EER as the average of FPR and FNR at that threshold
    eer = (fpr[eer_index] + fnr[eer_index]) / 2

    return eer, eer_threshold

In [110]:

eer, eer_threshold = compute_eer(y_train, probs_train)
print(f"EER (Average of FPR & FNR): {eer:.4f}, Threshold: {eer_threshold:.4f}")

EER (Average of FPR & FNR): 0.1252, Threshold: 0.6353

In [16]:
from sklearn.metrics import confusion_matrix
import numpy as np

def compute_eer_fixed_threshold(y_true, y_scores, threshold):
    """
    Compute the Equal Error Rate (EER) at a fixed threshold.
    
    Parameters:
    - y_true: array-like of shape (n_samples,) -> True binary labels (0 or 1)
    - y_scores: array-like of shape (n_samples,) -> Predicted scores/probabilities
    - threshold: float, the fixed threshold at which to compute EER
    
    Returns:
    - eer: float, the average of FPR and FNR at the fixed threshold
    """
    # Convert scores to binary predictions using the fixed threshold
    y_pred = (y_scores >= threshold).astype(int)
    
    # Compute confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
    # Compute False Positive Rate (FPR) and False Negative Rate (FNR)
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0
    
    # Compute EER as the average of FPR and FNR
    eer = (fpr + fnr) / 2
    
    return eer

In [111]:
eer_test = compute_eer_fixed_threshold(y_test, probs_test, 0.6353)

In [112]:
eer_test

np.float64(0.5055904504635829)

In [ ]:
/umbc/rs/iharp/users/zkhanja1/converted_wavs_df_7000

In [20]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

Fake vs real Detection using HuBERT:

In [17]:
y_test1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_xlsr_ITW_0to5000.xlsx')

In [18]:
y_test2 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_xlsr_ITW_5000to10000.xlsx')

In [19]:
y_test3= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_xlsr_ITW_10000to15000.xlsx')

In [20]:
y_test4= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_xlsr_ITW_15000to20000.xlsx')

In [21]:
y_test5= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_xlsr_ITW_20000to25000.xlsx')

In [22]:
y_test6= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_xlsr_ITW_25000to31777.xlsx')

In [24]:
 y_train1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_xlsr_df_flac_T_aa_asvspoof5_0to7000.xlsx')

In [22]:
#y_train2= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_xlsr_df_T_3001to7000.xlsx')

In [25]:
y_test = pd.concat([y_test1, y_test2, y_test3, y_test4, y_test5, y_test6], ignore_index=True)

In [26]:
y_train = y_train1

In [38]:
y_test

      audio_filenames
0               0.wav
1               1.wav
2              10.wav
3             100.wav
4            1000.wav
...               ...
31772        9993.wav
31773        9994.wav
31774        9995.wav
31775        9996.wav
31776        9997.wav

[31777 rows x 1 columns]

In [26]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6995  T_0000006995.flac
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac

[7000 rows x 1 columns]

In [ ]:
 #Df_train_with_labels.csv

In [ ]:
 #Df_eval_all_parts_with_labels.csv

In [31]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes'

In [28]:
Df_train_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/asvspoof5/protocols/ASVspoof5.train.tsv', sep=' ', header=None)

In [29]:
Df_train_with_labels

                        0  1  2  3  4    5         6         7  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [30]:
Df_train_with_labels.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [30]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes_and_ITW'

In [31]:
 Df_eval_all_parts_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/meta.csv')

In [32]:
Df_eval_all_parts_with_labels

            file                speaker      label
0          0.wav          Alec Guinness      spoof
1          1.wav          Alec Guinness      spoof
2          2.wav           Barack Obama      spoof
3          3.wav          Alec Guinness      spoof
4          4.wav   Christopher Hitchens  bona-fide
...          ...                    ...        ...
31774  31774.wav          Boris Johnson  bona-fide
31775  31775.wav           Donald Trump  bona-fide
31776  31776.wav           Donald Trump  bona-fide
31777  31777.wav             Alan Watts  bona-fide
31778  31778.wav  Arnold Schwarzenegger      spoof

[31779 rows x 3 columns]

In [33]:
Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={'file': 'audio_filenames'})

In [39]:
Df_eval_all_parts_with_labels

      audio_filenames                speaker      label
0               0.wav          Alec Guinness      spoof
1               1.wav          Alec Guinness      spoof
2               2.wav           Barack Obama      spoof
3               3.wav          Alec Guinness      spoof
4               4.wav   Christopher Hitchens  bona-fide
...               ...                    ...        ...
31774       31774.wav          Boris Johnson  bona-fide
31775       31775.wav           Donald Trump  bona-fide
31776       31776.wav           Donald Trump  bona-fide
31777       31777.wav             Alan Watts  bona-fide
31778       31778.wav  Arnold Schwarzenegger      spoof

[31779 rows x 3 columns]

In [35]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac
7000  T_0000007000.flac

[7001 rows x 1 columns]

In [87]:

#y_train['audio_filenames'] = y_train['audio_filenames'].str.replace('.flac', '', regex=False)

# 2. Rename 'FileName' column to 'audio_filenames' in Df_train_with_labels
#Df_train_with_labels = Df_train_with_labels.rename(columns={0: 'audio_filenames'})
#Df_train_with_labels = Df_train_with_labels.rename(columns={7: 'Label'})

In [42]:
Df_train_with_labels = Df_train_with_labels.rename(columns={0: 'audio_filenames'})

In [43]:
Df_train_with_labels

          audio_filenames  1  2  3  4    5         6         7  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [44]:
Df_train_with_labels['audio_filenames'] = Df_train_with_labels['audio_filenames'].str.replace('.flac', '', regex=False)

In [45]:
Df_train_with_labels

       audio_filenames  1  2  3  4    5         6         7  8
0         T_0000000000  F  -  -  -  AC3       A05     spoof  -
1         T_0000000001  M  -  -  -  AC3       A07     spoof  -
2         T_0000000002  M  -  -  -  AC2       A04     spoof  -
3         T_0000000003  M  -  -  -  AC2       A08     spoof  -
4         T_0000000004  M  -  -  -  AC2       A05     spoof  -
...                ... .. .. .. ..  ...       ...       ... ..
182352    T_0000182352  F  -  -  -  AC2       A03     spoof  -
182353    T_0000182353  M  -  -  -  AC2       A05     spoof  -
182354    T_0000182354  M  -  -  -  AC3       A02     spoof  -
182355    T_0000182355  M  -  -  -    -  bonafide  bonafide  -
182356    T_0000182356  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [46]:
Df_train_with_labels = Df_train_with_labels.rename(columns={7: 'Label'})

In [48]:
Df_eval_all_parts_with_labels['audio_filenames'] = Df_eval_all_parts_with_labels['audio_filenames'].str.replace('.wav', '', regex=False)

In [52]:
y_train['audio_filenames'] = y_train['audio_filenames'].str.replace('.flac', '', regex=False)

In [51]:
Df_train_with_labels

       audio_filenames  1  2  3  4    5         6     Label  8
0         T_0000000000  F  -  -  -  AC3       A05     spoof  -
1         T_0000000001  M  -  -  -  AC3       A07     spoof  -
2         T_0000000002  M  -  -  -  AC2       A04     spoof  -
3         T_0000000003  M  -  -  -  AC2       A08     spoof  -
4         T_0000000004  M  -  -  -  AC2       A05     spoof  -
...                ... .. .. .. ..  ...       ...       ... ..
182352    T_0000182352  F  -  -  -  AC2       A03     spoof  -
182353    T_0000182353  M  -  -  -  AC2       A05     spoof  -
182354    T_0000182354  M  -  -  -  AC3       A02     spoof  -
182355    T_0000182355  M  -  -  -    -  bonafide  bonafide  -
182356    T_0000182356  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [53]:
# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_train_new = y_train.merge(Df_train_with_labels[['audio_filenames', 'Label']], 
                            on='audio_filenames', 
                            how='left')

In [54]:
y_train_new

     audio_filenames     Label
0       T_0000000000     spoof
1       T_0000000001     spoof
2       T_0000000002     spoof
3       T_0000000003     spoof
4       T_0000000004     spoof
...              ...       ...
6996    T_0000006996     spoof
6997    T_0000006997     spoof
6998    T_0000006998  bonafide
6999    T_0000006999     spoof
7000    T_0000007000     spoof

[7001 rows x 2 columns]

In [55]:
null_count = y_train_new['Label'].isnull().sum()

print(f"Number of missing 'Label' values in y_train_new: {null_count}")

Number of missing 'Label' values in y_train_new: 0

In [56]:
y_test

      audio_filenames
0               0.wav
1               1.wav
2              10.wav
3             100.wav
4            1000.wav
...               ...
31772        9993.wav
31773        9994.wav
31774        9995.wav
31775        9996.wav
31776        9997.wav

[31777 rows x 1 columns]

In [57]:
Df_eval_all_parts_with_labels

      audio_filenames                speaker      label
0                   0          Alec Guinness      spoof
1                   1          Alec Guinness      spoof
2                   2           Barack Obama      spoof
3                   3          Alec Guinness      spoof
4                   4   Christopher Hitchens  bona-fide
...               ...                    ...        ...
31774           31774          Boris Johnson  bona-fide
31775           31775           Donald Trump  bona-fide
31776           31776           Donald Trump  bona-fide
31777           31777             Alan Watts  bona-fide
31778           31778  Arnold Schwarzenegger      spoof

[31779 rows x 3 columns]

In [58]:
y_test['audio_filenames'] = y_test['audio_filenames'].str.replace('.wav', '', regex=False)

In [44]:



# 2. Rename 'FileName' column to 'audio_filenames' in Df_train_with_labels
#Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={1: 'audio_filenames'})
#Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={8: 'Label'})

In [59]:
Df_eval_all_parts_with_labels

      audio_filenames                speaker      label
0                   0          Alec Guinness      spoof
1                   1          Alec Guinness      spoof
2                   2           Barack Obama      spoof
3                   3          Alec Guinness      spoof
4                   4   Christopher Hitchens  bona-fide
...               ...                    ...        ...
31774           31774          Boris Johnson  bona-fide
31775           31775           Donald Trump  bona-fide
31776           31776           Donald Trump  bona-fide
31777           31777             Alan Watts  bona-fide
31778           31778  Arnold Schwarzenegger      spoof

[31779 rows x 3 columns]

In [46]:
y_test

      audio_filenames
0                   0
1                   1
2                  10
3                 100
4                1000
...               ...
31772            9993
31773            9994
31774            9995
31775            9996
31776            9997

[31777 rows x 1 columns]

In [60]:
# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_test_new = y_test.merge(Df_eval_all_parts_with_labels[['audio_filenames', 'label']], 
                            on='audio_filenames', 
                            how='left')

In [61]:
y_test_new

      audio_filenames      label
0                   0      spoof
1                   1      spoof
2                  10      spoof
3                 100  bona-fide
4                1000  bona-fide
...               ...        ...
31772            9993      spoof
31773            9994  bona-fide
31774            9995      spoof
31775            9996  bona-fide
31776            9997      spoof

[31777 rows x 2 columns]

In [62]:
# Check for null values in the 'Label' column
null_count = y_test_new['label'].isnull().sum()

print(f"Number of missing 'Label' values in y_test_new: {null_count}")

Number of missing 'Label' values in y_test_new: 0

In [63]:
y_train_new.to_csv('asvspoof5_DF_labels_corresponding_to_xlsr_7000_train_for_ITW.csv')

In [64]:
y_test_new.to_csv('ITW_labels_corresponding_to_xlsr.csv')

In [77]:
y_train = pd.read_csv('asvspoof5_DF_labels_corresponding_to_xlsr_7000_train_for_ITW.csv')

In [78]:
y_test = pd.read_csv('ITW_labels_corresponding_to_xlsr.csv')

In [65]:
len(y_test)

31777

In [54]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes_and_ITW'

In [66]:

X_test1 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/xlsr_hidden_states_ITW_0to5000.npy')
X_test2=np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/xlsr_hidden_states_ITW_5000to10000.npy')
X_test3 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/xlsr_hidden_states_ITW_10000to15000.npy')
X_test4= np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/xlsr_hidden_states_ITW_15000to20000.npy')
X_test5=np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/xlsr_hidden_states_ITW_20000to25000.npy')
X_test6=np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/xlsr_hidden_states_ITW_25000to31777.npy')
#X_test3 = np.load('/umbc/rs/iharp/users/zkhanja1/npy_files/HuBERT_hidden_states_df_eval_7000_4000to7000.npy')

# Concatenate them in order
X_test = np.concatenate((X_test1, X_test2, X_test3, X_test4, X_test5, X_test6), axis=0)

# Save X_test to a new .npy file if needed
# np.save('X_test.npy', X_test)

In [68]:
print(f"Shape of X_test: {X_test.shape}")

Shape of X_test: (31777, 549, 1024)

In [69]:
pd

In [23]:
#X_test2 = X_test[:7000]

In [24]:
#X_test2.shape

In [70]:
import numpy as np

# Load the .npy files for X_train
X_train1 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/xlsr_hidden_states_df_flac_T_aa_asvspoof5_0to7000.npy')
#X_train2 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/HuBERT_hidden_states_df_T_3001to7000.npy')
#X_train3 = np.load('/umbc/rs/iharp/users/zkhanja1/npy_files/HuBERT_hidden_states_df_train_7000_4000to7000.npy')

# Concatenate them in order


# Print the shape of X_train
#print(f"Shape of X_train: {X_train.shape}")

In [71]:
X_train = X_train1

In [72]:
print(f"Shape of X_train: {X_train.shape}")

Shape of X_train: (7001, 549, 1024)

In [73]:
y_train

     audio_filenames
0       T_0000000000
1       T_0000000001
2       T_0000000002
3       T_0000000003
4       T_0000000004
...              ...
6996    T_0000006996
6997    T_0000006997
6998    T_0000006998
6999    T_0000006999
7000    T_0000007000

[7001 rows x 1 columns]

In [79]:
y_train_new = y_train
y_test_new = y_test

In [80]:
y_test

       Unnamed: 0  audio_filenames      label
0               0                0      spoof
1               1                1      spoof
2               2               10      spoof
3               3              100  bona-fide
4               4             1000  bona-fide
...           ...              ...        ...
31772       31772             9993      spoof
31773       31773             9994  bona-fide
31774       31774             9995      spoof
31775       31775             9996  bona-fide
31776       31776             9997      spoof

[31777 rows x 3 columns]

In [81]:
# For y_train_new
y_train = y_train_new['Label'].map({'spoof': 1, 'bonafide': 0})
print(f"First few y_train values:\n{y_train.head()}")

First few y_train values:
0    1
1    1
2    1
3    1
4    1
Name: Label, dtype: int64

In [32]:
#y_test_new = Df_eval_all_parts_with_labels

In [82]:
# For y_test_new
y_test = y_test_new['label'].map({'spoof': 1, 'bona-fide': 0})
print(f"First few y_test values:\n{y_test.head()}")

First few y_test values:
0    1
1    1
2    1
3    0
4    0
Name: label, dtype: int64

In [83]:
# Calculate the percentage of 1s in y_train
percentage_1_train = (y_train == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_train: {percentage_1_train:.2f}%")

# Calculate the percentage of 1s in y_test
percentage_1_test = (y_test == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_test: {percentage_1_test:.2f}%")

Percentage of '1' (spoof) in y_train: 89.36%
Percentage of '1' (spoof) in y_test: 37.18%

In [81]:
!pip install --upgrade scikit-learn
!pip install --upgrade imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imbalanced-learn in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (0.11.0)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.13.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy<3,>=1.24.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy<2,>=1.10.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.15.2)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.6.1)
Collecting sklearn-compat<1,>=0.1 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: joblib<2,>=1.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.13.0-py3-none-any.whl (238 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.4/238.4 kB 5.4 MB/s eta 0:00:00:00:01
Downloading sklearn_compat-0.1.3-py3-none-any.whl (18 kB)
Installing collected packages: sklearn-compat, imbalanced-learn
Successfully installed imbalanced-learn-0.13.0 sklearn-compat-0.1.3

In [84]:
from imblearn.over_sampling import SMOTE

# First, ensure y_train is a numpy array if it's not already
y_train_np = y_train.values if hasattr(y_train, 'values') else y_train

# Apply SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train.reshape(X_train.shape[0], -1), y_train_np)

# If needed, reshape X_train_resampled back to original dimensions
X_train_resampled = X_train_resampled.reshape(-1, X_train.shape[1], X_train.shape[2])

# Print new class distribution
print(f"Resampled class distribution:\n{pd.Series(y_train_resampled).value_counts()}")

Resampled class distribution:
1    6256
0    6256
Name: count, dtype: int64

In [85]:
from sklearn.model_selection import train_test_split

# Use 10% of the original X_train and y_train as validation
#X_train_sub, X_val, y_train_sub, y_val = train_test_split(
#    X_train, y_train, test_size=0.1, random_state=42, stratify=y_train
#)

In [86]:
from tensorflow.keras.metrics import AUC

In [87]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam

In [113]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam

# Flatten input shape for MLP
input_dim = X_train_resampled.shape[1] * X_train_resampled.shape[2]

model = Sequential([
    Flatten(input_shape=(X_train_resampled.shape[1], X_train_resampled.shape[2])),
    Dense(128, activation='relu'),
   # Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.6),
    Dense(1, activation='sigmoid')
])



model.compile(
    optimizer=Adam(learning_rate=0.001), 
    loss='binary_crossentropy', 
    metrics=[AUC(name='roc_auc')]
)

In [1]:
 X_train.shape

NameError: name 'X_train' is not defined

In [116]:
X_train_resampled = np.squeeze(X_train_resampled, axis=1)
X_train = np.squeeze(X_train, axis=1)
X_test= np.squeeze(X_test, axis=1)

In [ ]:
history = model.fit(
    X_train_resampled, y_train_resampled,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

In [100]:
# Get probabilities for original X_train and X_test
probs_train = model.predict(X_train)
probs_test = model.predict(X_test)

print(f"First 5 probabilities on X_train:\n{probs_train[:5].flatten()}")
print(f"First 5 probabilities on X_test:\n{probs_test[:5].flatten()}")

215/219 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2025-11-08 11:24:21.530211: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2025-11-08 11:24:21.530431: W external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:1008] Compiling 41 configs for 2 fusions on a single thread.
2025-11-08 11:24:23.116090: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_17', 292 bytes spill stores, 292 bytes spill loads

219/219 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step
First 5 probabilities on X_train:
[1.         1.         0.99999475 0.99999905 0.9999999 ]
First 5 probabilities on X_test:
[1. 1. 1. 1. 1.]

In [41]:
len(X_test)

6998

In [40]:
y_test

0       1
1       1
2       1
3       1
4       1
       ..
6994    1
6995    1
6996    1
6997    1
6998    1
Name: Label, Length: 6999, dtype: int64

In [101]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on training data: 0.9999
ROC AUC on test data: 0.5221

In [58]:
probs_test

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [59]:
unique_values = np.unique(probs_test)
print(unique_values)

[1.11031072e-17 2.00934760e-17 2.14623806e-17 4.43134749e-17
 5.05572129e-17 7.02908769e-17 1.31468513e-16 1.35873270e-16
 1.71125524e-16 1.82784456e-16 2.15523934e-16 4.30567388e-16
 7.05856801e-16 7.79204931e-16 8.32292933e-16 1.89700059e-15
 2.68126839e-15 3.72783054e-15 5.09819856e-15 6.11127156e-15
 6.21281684e-15 6.74631588e-15 9.07552943e-15 9.85488953e-15
 1.01850689e-14 1.16200952e-14 1.28276042e-14 1.72563939e-14
 2.13784170e-14 2.39920592e-14 2.64851092e-14 3.22754281e-14
 3.86888634e-14 3.93316463e-14 4.71472328e-14 5.20464680e-14
 6.03662086e-14 9.11360966e-14 1.12905690e-13 1.22601243e-13
 1.94472436e-13 2.04327305e-13 2.14681585e-13 4.89311282e-13
 7.03095243e-13 7.50997842e-13 1.02706808e-12 1.15262921e-12
 1.17177915e-12 1.25160873e-12 1.31503142e-12 1.71170901e-12
 1.76905181e-12 1.85869484e-12 1.88958267e-12 2.41936809e-12
 2.67077332e-12 3.30874542e-12 3.36371079e-12 4.30682486e-12
 4.91364371e-12 5.51434679e-12 5.79377475e-12 5.89002241e-12
 6.61010136e-12 6.76369421e-12 7.66675525e-12 8.60403155e-12
 8.89228535e-12 9.49810716e-12 1.11994060e-11 1.21611532e-11
 1.38746540e-11 1.43394576e-11 1.48198901e-11 1.48285412e-11
 1.53164183e-11 1.77647463e-11 2.46987899e-11 2.51090902e-11
 2.86469477e-11 2.91228881e-11 3.37782441e-11 3.85375030e-11
 4.11629481e-11 4.39674130e-11 4.61952837e-11 4.85361334e-11
 5.01623014e-11 5.27040737e-11 6.52935761e-11 7.09005146e-11
 7.57308868e-11 8.36003697e-11 1.43995982e-10 1.48820442e-10
 1.53806259e-10 1.69788822e-10 2.17393631e-10 2.32203978e-10
 2.43970899e-10 2.52144472e-10 2.64920863e-10 3.07269044e-10
 3.12374626e-10 3.17563809e-10 3.22839255e-10 3.28203548e-10
 3.39198475e-10 3.68327091e-10 4.06601308e-10 4.79431606e-10
 5.03725839e-10 5.56069801e-10 5.74700454e-10 6.24051644e-10
 6.44958753e-10 6.77640721e-10 7.21226467e-10 7.48056839e-10
 8.12296119e-10 8.38445757e-10 8.82050266e-10 1.28847966e-09
 1.59625779e-09 1.91345362e-09 2.40990294e-09 2.44994136e-09
 2.61684785e-09 2.93676838e-09 3.03515657e-09 3.32429906e-09
 3.35055117e-09 3.40621731e-09 3.57882035e-09 3.63827901e-09
 3.76016951e-09 4.92095742e-09 6.04262684e-09 1.14024212e-08
 1.60439928e-08 1.75678565e-08 3.61749386e-08 3.64234261e-08
 3.74495492e-08 4.07192324e-08 4.20982644e-08 4.22731183e-08
 4.47675816e-08 4.60144562e-08 5.19466568e-08 5.20670831e-08
 7.69944961e-08 1.04878495e-07 1.12655862e-07 1.19746105e-07
 2.43198116e-07 3.06885767e-07 3.31506953e-07 3.50007610e-07
 6.30586328e-07 8.52353537e-07 8.71388977e-07 9.65923959e-07
 1.22670986e-06 2.43145314e-06 2.87746138e-06 3.53684891e-06
 3.79142330e-06 5.30005991e-06 1.10021174e-05 1.28825068e-05
 1.71441407e-05 2.46290583e-05 2.75309376e-05 5.23512717e-05
 5.84526388e-05 5.89124647e-05 6.08146693e-05 8.28350239e-05
 8.36295949e-05 9.63739658e-05 1.04346982e-04 1.05793122e-04
 1.10904155e-04 1.18482189e-04 1.20084485e-04 1.26263694e-04
 1.27616833e-04 1.44743361e-04 2.22390270e-04 2.40236433e-04
 3.04730347e-04 3.68531997e-04 4.95069718e-04 6.12986565e-04
 6.24429551e-04 8.08415178e-04 8.90317140e-04 1.18275185e-03
 1.26494782e-03 1.45422632e-03 1.76866062e-03 2.42890161e-03
 2.98068835e-03 3.30089848e-03 4.23149113e-03 4.37520444e-03
 5.17069083e-03 5.25547797e-03 7.25933677e-03 7.78580178e-03
 7.81377405e-03 7.96654634e-03 8.41393974e-03 8.59746709e-03
 8.66804458e-03 9.85148456e-03 1.02110831e-02 1.20752510e-02
 1.20810661e-02 1.29451565e-02 1.32084759e-02 1.49156172e-02
 1.60416607e-02 1.66978668e-02 1.69647411e-02 1.70290582e-02
 1.88513435e-02 1.89143457e-02 2.01280732e-02 2.03846581e-02
 2.21624244e-02 2.34067291e-02 2.44516693e-02 2.66416837e-02
 2.70943940e-02 3.28009166e-02 4.00415882e-02 4.11027670e-02
 4.29294296e-02 4.96554971e-02 5.01117967e-02 5.22098802e-02
 5.56058027e-02 5.58568873e-02 5.86716384e-02 5.91450743e-02
 5.96049912e-02 6.10633157e-02 6.18660375e-02 6.21044785e-02
 6.23555109e-02 6.42025918e-02 6.45648092e-02 6.52926713e-02
 6.54272065e-02 6.61016852e-02 6.66174442e-02 6.71637580e-02
 6.74839839e-02 7.12887645e-02 7.13771954e-02 7.13962168e-02
 7.40214884e-02 7.46818185e-02 7.55632073e-02 7.62739331e-02
 7.72374272e-02 7.82877803e-02 7.83247799e-02 7.89871588e-02
 8.10869262e-02 8.10930878e-02 8.55037794e-02 8.77040103e-02
 8.84992406e-02 9.19975415e-02 9.53662470e-02 9.85710248e-02
 1.08506605e-01 1.14102677e-01 1.31337985e-01 1.44934207e-01
 1.62213251e-01 1.72214925e-01 1.75664261e-01 1.90198183e-01
 1.90385982e-01 1.99049175e-01 2.01939747e-01 2.94180632e-01
 3.40423763e-01 3.49381238e-01 3.75998795e-01 3.79417747e-01
 3.87744009e-01 4.19562072e-01 4.38980758e-01 4.78286505e-01
 5.01563430e-01 5.75188279e-01 6.10121906e-01 6.24641240e-01
 6.32822692e-01 6.43747807e-01 6.52251422e-01 6.74947798e-01
 7.00505137e-01 7.07642436e-01 7.23681867e-01 7.84746706e-01
 7.94607401e-01 7.97875106e-01 8.36382627e-01 8.47266257e-01
 8.85246634e-01 8.95809352e-01 9.12426353e-01 9.13586199e-01
 9.20096874e-01 9.24338460e-01 9.28384423e-01 9.41657901e-01
 9.58073497e-01 9.58560467e-01 9.65800941e-01 9.70418692e-01
 9.71064985e-01 9.71152544e-01 9.71931636e-01 9.77896333e-01
 9.80897069e-01 9.81195927e-01 9.84153211e-01 9.84827042e-01
 9.85842049e-01 9.91280854e-01 9.92953956e-01 9.94866371e-01
 9.94963586e-01 9.95188236e-01 9.95419562e-01 9.95928824e-01
 9.96048033e-01 9.96498466e-01 9.96513724e-01 9.96556222e-01
 9.97184217e-01 9.97402966e-01 9.97493386e-01 9.98035610e-01
 9.98141766e-01 9.98256624e-01 9.98280168e-01 9.98342752e-01
 9.98379707e-01 9.98461366e-01 9.98755813e-01 9.98857260e-01
 9.99016285e-01 9.99238729e-01 9.99240637e-01 9.99267995e-01
 9.99286056e-01 9.99458969e-01 9.99543130e-01 9.99615788e-01
 9.99712050e-01 9.99736130e-01 9.99746382e-01 9.99875665e-01
 9.99893785e-01 9.99906421e-01 9.99922395e-01 9.99943733e-01
 9.99945641e-01 9.99956250e-01 9.99957800e-01 9.99960780e-01
 9.99962926e-01 9.99963403e-01 9.99965072e-01 9.99965549e-01
 9.99985814e-01 9.99986768e-01 9.99992132e-01 9.99992371e-01
 9.99995112e-01 9.99995351e-01 9.99995828e-01 9.99995947e-01
 9.99996543e-01 9.99997616e-01 9.99997735e-01 9.99998450e-01
 9.99998569e-01 9.99999046e-01 9.99999166e-01 9.99999285e-01
 9.99999404e-01 9.99999523e-01 9.99999762e-01 9.99999881e-01
 1.00000000e+00]

In [61]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

307

In [88]:
# Assuming X_train shape is (samples, time_steps, features)
X_train_resampled = np.expand_dims(X_train_resampled, axis=1)  # (samples, 1, time_steps, features)
#X_val = np.expand_dims(X_val, axis=1)
X_train = np.expand_dims(X_train, axis=1)
X_test = np.expand_dims(X_test, axis=1)

In [89]:
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

def build_resnet18(input_shape):
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2D(64, 7, strides=2, padding='same', use_bias=False)(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D(3, strides=2, padding='same')(x)

    def residual_block(x, filters, downsample=False):
        shortcut = x
        strides = 2 if downsample else 1
        x = layers.Conv2D(filters, 3, strides=strides, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)
        x = layers.ReLU()(x)
        x = layers.Conv2D(filters, 3, strides=1, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)

        if downsample or shortcut.shape[-1] != filters:
            shortcut = layers.Conv2D(filters, 1, strides=strides, padding='same', use_bias=False,
                                     kernel_regularizer=regularizers.l2(1e-4))(shortcut)
            shortcut = layers.BatchNormalization()(shortcut)

        x = layers.add([x, shortcut])
        x = layers.ReLU()(x)
        return x

    x = residual_block(x, 64)
    x = residual_block(x, 64)
    x = residual_block(x, 128, downsample=True)
    x = residual_block(x, 128)
    x = residual_block(x, 256, downsample=True)
    x = residual_block(x, 256)
    x = residual_block(x, 512, downsample=True)
    x = residual_block(x, 512)

    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(1, activation='sigmoid')(x)

    model = models.Model(inputs, outputs)
    return model

input_shape = X_train_resampled.shape[1:]  # (time_steps, features, 1)
resnet18_model = build_resnet18(input_shape)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1768253488.617843  245765 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43489 MB memory:  -> device: 0, name: NVIDIA L40S, pci bus id: 0000:4a:00.0, compute capability: 8.9

In [90]:
from tensorflow.keras.optimizers import Adam

resnet18_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=[tf.keras.metrics.AUC(name='roc_auc')]
)

In [91]:
from tensorflow.keras.callbacks import EarlyStopping

# Define early stopping
early_stop = EarlyStopping(
    monitor='val_roc_auc',   # monitor validation AUC
    patience=5,              # stop if no improvement after 5 epochs
    mode='max',              # maximize AUC
    restore_best_weights=True  # restore the best model weights
)

In [92]:
history = resnet18_model.fit(
    X_train_resampled, y_train_resampled,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/50

2026-01-12 16:32:10.530955: I external/local_xla/xla/service/service.cc:163] XLA service 0x152f040217c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-01-12 16:32:10.530973: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA L40S, Compute Capability 8.9
2026-01-12 16:32:10.759268: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-01-12 16:32:12.214970: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91301

  7/333 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - loss: 1.0271 - roc_auc: 0.8013

I0000 00:00:1768253543.387334  337136 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

333/333 ━━━━━━━━━━━━━━━━━━━━ 39s 62ms/step - loss: 0.3607 - roc_auc: 0.9921 - val_loss: 0.9458 - val_roc_auc: 0.0000e+00
Epoch 2/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 15s 23ms/step - loss: 0.1943 - roc_auc: 0.9996 - val_loss: 0.1735 - val_roc_auc: 0.0000e+00
Epoch 3/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - loss: 0.1927 - roc_auc: 0.9992 - val_loss: 4.7886 - val_roc_auc: 0.0000e+00
Epoch 4/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - loss: 0.1730 - roc_auc: 1.0000 - val_loss: 0.1641 - val_roc_auc: 0.0000e+00
Epoch 5/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - loss: 0.1730 - roc_auc: 0.9994 - val_loss: 18.2500 - val_roc_auc: 0.0000e+00
Epoch 6/50
333/333 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - loss: 0.1572 - roc_auc: 1.0000 - val_loss: 0.1514 - val_roc_auc: 0.0000e+00

In [93]:
# Save full model (recommended)
resnet18_model.save("resnet18_model_xlsr_trained_on_asvspoof5_7000samples.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [22]:
import tensorflow as tf
from tensorflow.keras.models import load_model

In [24]:
resnet18_model = load_model("resnet18_model_xlsr_trained_on_asvspoof5_7000samples.h5")

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1767974749.453494 2219546 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 47184 MB memory:  -> device: 0, name: Quadro RTX 8000, pci bus id: 0000:1c:00.0, compute capability: 7.5
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [96]:
X_train = np.squeeze(X_train, axis=1)
X_test = np.squeeze(X_test, axis=1)

In [97]:
probs_train = resnet18_model.predict(X_train)

219/219 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step

In [ ]:
print(type(X_test))
print(X_test.dtype)
print(X_test.nbytes / 1024**3, "GB")

In [98]:
import numpy as np

batch_size = 8
probs_list = []

for i in range(0, len(X_test), batch_size):
    batch = X_test[i:i+batch_size]
    probs = resnet18_model.predict(batch, verbose=0)
    probs_list.append(probs)

probs_test = np.concatenate(probs_list, axis=0)

In [99]:
probs_test.shape

(31777, 1)

In [36]:
probs_train.shape

(7000, 1)

In [37]:
y_test.shape

(7000,)

In [63]:
probs_train

array([[1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       ...,
       [1.0000000e+00],
       [1.0591374e-06],
       [1.0000000e+00]], shape=(7000, 1), dtype=float32)

In [79]:
#y_test = y_test[:7000]

In [108]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

ROC AUC on training data: 0.9491

In [ ]:
#probs_test = resnet18_model.predict(X_test).flatten()

In [ ]:
len(probs_test)

In [109]:

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on test data: 0.4701

In [100]:
df_train_preds = pd.DataFrame({
    'audio_filenames': y_train_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_train.flatten()
})

In [101]:
df_train_preds

     audio_filenames  prob_spoof
0       T_0000000000    0.692673
1       T_0000000001    0.757853
2       T_0000000002    0.689329
3       T_0000000003    0.723493
4       T_0000000004    0.676550
...              ...         ...
6996    T_0000006996    0.722816
6997    T_0000006997    0.529187
6998    T_0000006998    0.586431
6999    T_0000006999    0.839899
7000    T_0000007000    0.609588

[7001 rows x 2 columns]

In [102]:
# Save train predictions
df_train_preds.to_csv('ITW_train_predictions_xlsr_resnet18_asvspoof5_as_train.csv', index=False)

In [103]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

122

In [104]:
# Create DataFrame for test predictions
df_test_preds = pd.DataFrame({
    'audio_filenames': y_test_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_test.flatten()
})

In [107]:
df_test_preds

       audio_filenames  prob_spoof
0                    0    0.786643
1                    1    0.737604
2                   10    0.726019
3                  100    0.779081
4                 1000    0.829804
...                ...         ...
31772             9993    0.794828
31773             9994    0.771972
31774             9995    0.801221
31775             9996    0.798714
31776             9997    0.715364

[31777 rows x 2 columns]

In [106]:
# Save test predictions
df_test_preds.to_csv('ITW_test_predictions_xlsr_resnet18.csv', index=False)