# ITW WavLM

In [5]:
import pandas as pd

In [6]:
pd

In [7]:
import tensorflow as tf

In [8]:
pd

In [6]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy<2,>=1.21 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install -U scikit-learn scipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: scipy in /home/zkhanja1/.local/lib/python3.11/site-packages (1.15.2)
Collecting scipy
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 58.2 MB/s eta 0:00:00:00:0100:01
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory '/umbc/rs/iharp/users/zkhanja1/.local/lib/python3.11/site-packages/~cipy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
Successfully installed scipy-1.15.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install librosa

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: librosa in /home/zkhanja1/.local/lib/python3.11/site-packages (0.11.0)
Requirement already satisfied: audioread>=2.1.9 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (3.0.1)
Requirement already satisfied: numba>=0.51.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.59.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.15.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.2.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (5.1.1)
Requirement already satisfied: soundfile>=0.12.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from librosa) (0.5.0.post1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (4.9.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (0.3)
Requirement already satisfied: msgpack>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from librosa) (1.0.3)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.51.0->librosa) (0.42.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (3.10.0)
Requirement already satisfied: packaging>=20.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (23.1)
Requirement already satisfied: requests>=2.19.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from pooch>=1.1->librosa) (2.31.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from soundfile>=0.12.1->librosa) (1.16.0)
Requirement already satisfied: pycparser in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2024.2.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install resampy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: resampy in /home/zkhanja1/.local/lib/python3.11/site-packages (0.4.3)
Requirement already satisfied: numpy>=1.17 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (1.26.4)
Requirement already satisfied: numba>=0.53 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from resampy) (0.59.0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from numba>=0.53->resampy) (0.42.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install tf_slim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tf_slim in /home/zkhanja1/.local/lib/python3.11/site-packages (1.1.0)
Requirement already satisfied: absl-py>=0.2.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from tf_slim) (2.2.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
from tensorflow.keras.models import Model
from tensorflow.keras import Input
from tensorflow.keras.layers import concatenate, Permute, Reshape
import os

In [10]:
import math
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential

In [11]:
#from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LSTM,TimeDistributed
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [12]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import BatchNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy as np
import sklearn.metrics as metrics

In [13]:
import pandas as pd
import math
import numpy as np
#from numpy.lib.function_base import average
import os
import librosa
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras import models, layers
import tensorflow as tf
from matplotlib.pyplot import specgram
import glob

In [14]:
from sklearn.metrics import confusion_matrix
import IPython.display as ipd  # To play sound in the notebook
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras
import sys
import warnings
# ignore warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)
import json

from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')

import pickle
import joblib
from tensorflow.keras import models, layers
import tensorflow as tf

In [9]:
import tensorflow as tf

# Simple operation
with tf.device('/GPU:0'):
    a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
    b = tf.constant([[1.0, 1.0], [0.0, 1.0]])
    c = tf.matmul(a, b)

print(c)

# Check where the tensor was placed
print("Operation executed on:", c.device)

I0000 00:00:1753043273.413141 2145353 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 47187 MB memory:  -> device: 0, name: Quadro RTX 8000, pci bus id: 0000:1d:00.0, compute capability: 7.5

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
Operation executed on: /job:localhost/replica:0/task:0/device:GPU:0

In [13]:
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available: 1

In [15]:
import tensorflow as tf
import librosa
import os

In [26]:
pip install ffmpeg

Defaulting to user installation because normal site-packages is not writeable
Collecting ffmpeg
  Downloading ffmpeg-1.4.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ffmpeg
  Building wheel for ffmpeg (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6082 sha256=9a34e0c2d141d532efe8a2a5039eaa8d21fb51146cc3f7feca77e7875c09df23
  Stored in directory: /umbc/rs/iharp/users/zkhanja1/.cache/pip/wheels/56/30/c5/576bdd729f3bc062d62a551be7fefd6ed2f761901568171e4e
Successfully built ffmpeg
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!module load FFmpeg/7.0.2-GCCcore-13.3.0

In [ ]:
import ffmpeg

In [ ]:
!ffmpeg -version

In [16]:
import numpy as np
from sklearn.metrics import roc_curve

def compute_eer(y_true, y_probs):
    """
    Computes the Equal Error Rate (EER) as the average of FPR and FNR.
    
    Parameters:
        y_true (array-like): True binary labels (0 or 1).
        y_probs (array-like): Predicted probabilities for the positive class.

    Returns:
        eer (float): Equal Error Rate (average of FPR and FNR).
        eer_threshold (float): Threshold where FPR and FNR are closest.
    """
    # Compute ROC curve
    fpr, tpr, thresholds = roc_curve(y_true, y_probs)

    # Compute False Negative Rate (FNR)
    fnr = 1 - tpr  # FNR = 1 - TPR

    # Find the threshold where FPR and FNR are closest
    eer_index = np.nanargmin(np.abs(fpr - fnr))  # Get index of min difference
    eer_threshold = thresholds[eer_index]

    # Compute EER as the average of FPR and FNR at that threshold
    eer = (fpr[eer_index] + fnr[eer_index]) / 2

    return eer, eer_threshold

In [84]:

eer, eer_threshold = compute_eer(y_train, probs_train)
print(f"EER (Average of FPR & FNR): {eer:.4f}, Threshold: {eer_threshold:.4f}")

EER (Average of FPR & FNR): 0.0000, Threshold: 0.6189

In [17]:
from sklearn.metrics import confusion_matrix
import numpy as np

def compute_eer_fixed_threshold(y_true, y_scores, threshold):
    """
    Compute the Equal Error Rate (EER) at a fixed threshold.
    
    Parameters:
    - y_true: array-like of shape (n_samples,) -> True binary labels (0 or 1)
    - y_scores: array-like of shape (n_samples,) -> Predicted scores/probabilities
    - threshold: float, the fixed threshold at which to compute EER
    
    Returns:
    - eer: float, the average of FPR and FNR at the fixed threshold
    """
    # Convert scores to binary predictions using the fixed threshold
    y_pred = (y_scores >= threshold).astype(int)
    
    # Compute confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
    # Compute False Positive Rate (FPR) and False Negative Rate (FNR)
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0
    
    # Compute EER as the average of FPR and FNR
    eer = (fpr + fnr) / 2
    
    return eer

In [85]:
eer_test = compute_eer_fixed_threshold(y_test, probs_test, 0.6189)

In [86]:
eer_test

0.1719582454743819

In [ ]:
/umbc/rs/iharp/users/zkhanja1/converted_wavs_df_7000

In [19]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes_and_ITW'

In [ ]:
asvspoof5/audio_filenames_for_HuBERT_df_eval_15000to20000.xlsx

Fake vs real Detection using WavLM:

In [20]:
y_test1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_WavLM_ITW_0to5000.xlsx')

In [23]:
y_train1 = pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_WavLM_df_T_0to5000.xlsx')

In [25]:
y_test2= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_WavLM_ITW_5000to10000.xlsx')

In [24]:
y_train2= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/asvspoof5/audio_filenames_for_WavLM_df_T_5000to7000.xlsx')

In [26]:
y_test3= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_WavLM_ITW_10000to15000.xlsx')

In [27]:
y_test4= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_WavLM_ITW_15000to20000.xlsx')

In [28]:
y_test5= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_WavLM_ITW_20000to25000.xlsx')

In [29]:
y_test6= pd.read_excel('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/audio_filenames_for_WavLM_ITW_25000to31777.xlsx')

In [23]:
#y_train3= pd.read_excel('audio_filenames_for_WavLM_df_train_7000_4000to7000.xlsx')

In [30]:
y_test = pd.concat([y_test1, y_test2, y_test3, y_test4, y_test5, y_test6], ignore_index=True)

In [31]:
y_train = pd.concat([y_train1, y_train2], ignore_index=True)

In [100]:
y_train_temp = pd.concat([y_train1, y_train2], ignore_index=True)

In [101]:
y_train_temp

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac
7000  T_0000007000.flac

[7001 rows x 1 columns]

In [32]:
y_test3

     audio_filenames
0          18999.wav
1             19.wav
2            190.wav
3           1900.wav
4          19000.wav
...              ...
4995       23493.wav
4996       23494.wav
4997       23495.wav
4998       23496.wav
4999       23497.wav

[5000 rows x 1 columns]

In [33]:
y_test

      audio_filenames
0               0.wav
1               1.wav
2              10.wav
3             100.wav
4            1000.wav
...               ...
31772        9993.wav
31773        9994.wav
31774        9995.wav
31775        9996.wav
31776        9997.wav

[31777 rows x 1 columns]

In [34]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac
7000  T_0000007000.flac

[7001 rows x 1 columns]

In [ ]:
 #Df_train_with_labels.csv

In [ ]:
 #Df_eval_all_parts_with_labels.csv

In [53]:
Df_train_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/asvspoof5/protocols/ASVspoof5.train.tsv', sep=' ', header=None)

In [36]:
Df_train_with_labels

                        0  1  2  3  4    5         6         7  8
0       T_0000000000.flac  F  -  -  -  AC3       A05     spoof  -
1       T_0000000001.flac  M  -  -  -  AC3       A07     spoof  -
2       T_0000000002.flac  M  -  -  -  AC2       A04     spoof  -
3       T_0000000003.flac  M  -  -  -  AC2       A08     spoof  -
4       T_0000000004.flac  M  -  -  -  AC2       A05     spoof  -
...                   ... .. .. .. ..  ...       ...       ... ..
182352  T_0000182352.flac  F  -  -  -  AC2       A03     spoof  -
182353  T_0000182353.flac  M  -  -  -  AC2       A05     spoof  -
182354  T_0000182354.flac  M  -  -  -  AC3       A02     spoof  -
182355  T_0000182355.flac  M  -  -  -    -  bonafide  bonafide  -
182356  T_0000182356.flac  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [37]:
 Df_eval_all_parts_with_labels = pd.read_csv('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/meta.csv')

In [39]:
Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={'file': 'audio_filenames'})

In [54]:
Df_train_with_labels = Df_train_with_labels.rename(columns={0: 'audio_filenames'})

In [64]:
y_train

        audio_filenames
0     T_0000000000.flac
1     T_0000000001.flac
2     T_0000000002.flac
3     T_0000000003.flac
4     T_0000000004.flac
...                 ...
6996  T_0000006996.flac
6997  T_0000006997.flac
6998  T_0000006998.flac
6999  T_0000006999.flac
7000  T_0000007000.flac

[7001 rows x 1 columns]

In [62]:
Df_train_with_labels['audio_filenames'] = Df_train_with_labels['audio_filenames'].str.replace('.flac', '', regex=False)

In [65]:
y_train['audio_filenames'] = y_train['audio_filenames'].str.replace('.flac', '', regex=False)

In [46]:
Df_eval_all_parts_with_labels['audio_filenames'] = Df_eval_all_parts_with_labels['audio_filenames'].str.replace('.wav', '', regex=False)

In [57]:
Df_train_with_labels = Df_train_with_labels.rename(columns={7: 'Label'})

In [58]:
Df_train_with_labels

       audio_filenames  1  2  3  4    5         6     Label  8
0         T_0000000000  F  -  -  -  AC3       A05     spoof  -
1         T_0000000001  M  -  -  -  AC3       A07     spoof  -
2         T_0000000002  M  -  -  -  AC2       A04     spoof  -
3         T_0000000003  M  -  -  -  AC2       A08     spoof  -
4         T_0000000004  M  -  -  -  AC2       A05     spoof  -
...                ... .. .. .. ..  ...       ...       ... ..
182352    T_0000182352  F  -  -  -  AC2       A03     spoof  -
182353    T_0000182353  M  -  -  -  AC2       A05     spoof  -
182354    T_0000182354  M  -  -  -  AC3       A02     spoof  -
182355    T_0000182355  M  -  -  -    -  bonafide  bonafide  -
182356    T_0000182356  M  -  -  -  AC2       A06     spoof  -

[182357 rows x 9 columns]

In [86]:
# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_train_new = y_train.merge(Df_train_with_labels[['audio_filenames', 'Label']], 
                            on='audio_filenames', 
                            how='left')

In [87]:
y_train_new

     audio_filenames     Label
0       T_0000000000     spoof
1       T_0000000001     spoof
2       T_0000000002     spoof
3       T_0000000003     spoof
4       T_0000000004     spoof
...              ...       ...
6996    T_0000006996     spoof
6997    T_0000006997     spoof
6998    T_0000006998  bonafide
6999    T_0000006999     spoof
7000    T_0000007000     spoof

[7001 rows x 2 columns]

In [68]:
null_count = y_train_new['Label'].isnull().sum()

print(f"Number of missing 'Label' values in y_train_new: {null_count}")

Number of missing 'Label' values in y_train_new: 0

In [69]:
y_test

      audio_filenames
0               0.wav
1               1.wav
2              10.wav
3             100.wav
4            1000.wav
...               ...
31772        9993.wav
31773        9994.wav
31774        9995.wav
31775        9996.wav
31776        9997.wav

[31777 rows x 1 columns]

In [71]:
Df_eval_all_parts_with_labels

      audio_filenames                speaker      label
0                   0          Alec Guinness      spoof
1                   1          Alec Guinness      spoof
2                   2           Barack Obama      spoof
3                   3          Alec Guinness      spoof
4                   4   Christopher Hitchens  bona-fide
...               ...                    ...        ...
31774           31774          Boris Johnson  bona-fide
31775           31775           Donald Trump  bona-fide
31776           31776           Donald Trump  bona-fide
31777           31777             Alan Watts  bona-fide
31778           31778  Arnold Schwarzenegger      spoof

[31779 rows x 3 columns]

In [88]:

y_test['audio_filenames'] = y_test['audio_filenames'].str.replace('.wav', '', regex=False)

# 2. Rename 'FileName' column to 'audio_filenames' in Df_train_with_labels
Df_eval_all_parts_with_labels = Df_eval_all_parts_with_labels.rename(columns={'FileName': 'audio_filenames'})

# 3. Merge the two dataframes based on 'audio_filenames', keeping y_train's order
y_test_new = y_test.merge(Df_eval_all_parts_with_labels[['audio_filenames', 'label']], 
                            on='audio_filenames', 
                            how='left')

In [89]:
y_test_new

      audio_filenames      label
0                   0      spoof
1                   1      spoof
2                  10      spoof
3                 100  bona-fide
4                1000  bona-fide
...               ...        ...
31772            9993      spoof
31773            9994  bona-fide
31774            9995      spoof
31775            9996  bona-fide
31776            9997      spoof

[31777 rows x 2 columns]

In [75]:
# Check for null values in the 'Label' column
null_count = y_test_new['label'].isnull().sum()

print(f"Number of missing 'Label' values in y_test_new: {null_count}")

Number of missing 'Label' values in y_test_new: 0

In [76]:
y_train_new.to_csv('DF_labels_corresponding_to_wavlm_7000_train_asvspoof5_forITW.csv')

In [77]:
y_test_new.to_csv('DF_labels_corresponding_to_wavlm_ITW.csv')

In [42]:
y_train = pd.read_csv('DF_labels_corresponding_to_wavlm_7000_train_asvspoof5_forITW.csv')

In [43]:
y_test = pd.read_csv('DF_labels_corresponding_to_wavlm_ITW.csv')

In [78]:
pwd

'/umbc/rs/iharp/users/zkhanja1/asvspoof5_codes_and_ITW'

In [79]:

X_test1 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/WavLM_hidden_states_ITW_0to5000.npy')
X_test2 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/WavLM_hidden_states_ITW_5000to10000.npy')
X_test3 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/WavLM_hidden_states_ITW_10000to15000.npy')
X_test4 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/WavLM_hidden_states_ITW_15000to20000.npy')
X_test5 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/WavLM_hidden_states_ITW_20000to25000.npy')
X_test6 = np.load('/umbc/rs/iharp/users/zkhanja1/in_the_wild_more_files/WavLM_hidden_states_ITW_25000to31777.npy')

# Concatenate them in order
X_test = np.concatenate((X_test1, X_test2, X_test3, X_test4, X_test5, X_test6), axis=0)

In [80]:
print(f"Shape of X_test: {X_test.shape}")

Shape of X_test: (31777, 549, 768)

In [81]:
import numpy as np

# Load the .npy files for X_train
X_train1 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/WavLM_hidden_states_df_T_0to5000.npy')
X_train2 = np.load('/umbc/rs/iharp/users/zkhanja1/asvspoof5/WavLM_hidden_states_df_T_5000to7000.npy')


# Concatenate them in order
X_train = np.concatenate((X_train1, X_train2), axis=0)

# Print the shape of X_train
print(f"Shape of X_train: {X_train.shape}")

Shape of X_train: (7208, 549, 768)

In [103]:
X_train2.shape

(2001, 549, 768)

In [13]:
y_train = pd.read_csv('DF_labels_corresponding_to_wavlm_7000_train.csv')

In [14]:
y_test = pd.read_csv('DF_labels_corresponding_to_wavlm_7000_test.csv')

In [15]:
y_train

      Unnamed: 0 audio_filenames     Label
0              0    LA_T_1000137     spoof
1              1    LA_T_1000406  bonafide
2              2    LA_T_1000648     spoof
3              3    LA_T_1000824     spoof
4              4    LA_T_1001074     spoof
...          ...             ...       ...
6994        6994    LA_T_3469583     spoof
6995        6995    LA_T_3469591     spoof
6996        6996    LA_T_3469711     spoof
6997        6997    LA_T_3470036     spoof
6998        6998    LA_T_3470152  bonafide

[6999 rows x 3 columns]

In [82]:
#y_train_new = y_train
#y_test_new = y_test

In [91]:
y_train_new

     audio_filenames     Label
0       T_0000000000     spoof
1       T_0000000001     spoof
2       T_0000000002     spoof
3       T_0000000003     spoof
4       T_0000000004     spoof
...              ...       ...
6996    T_0000006996     spoof
6997    T_0000006997     spoof
6998    T_0000006998  bonafide
6999    T_0000006999     spoof
7000    T_0000007000     spoof

[7001 rows x 2 columns]

In [92]:
# For y_train_new
y_train = y_train_new['Label'].map({'spoof': 1, 'bonafide': 0})
print(f"First few y_train values:\n{y_train.head()}")

First few y_train values:
0    1
1    1
2    1
3    1
4    1
Name: Label, dtype: int64

In [93]:
y_test_new

      audio_filenames      label
0                   0      spoof
1                   1      spoof
2                  10      spoof
3                 100  bona-fide
4                1000  bona-fide
...               ...        ...
31772            9993      spoof
31773            9994  bona-fide
31774            9995      spoof
31775            9996  bona-fide
31776            9997      spoof

[31777 rows x 2 columns]

In [95]:
# For y_test_new
y_test = y_test_new['label'].map({'spoof': 1, 'bona-fide': 0})
print(f"First few y_test values:\n{y_test.head()}")

First few y_test values:
0    1
1    1
2    1
3    0
4    0
Name: label, dtype: int64

In [96]:
# Calculate the percentage of 1s in y_train
percentage_1_train = (y_train == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_train: {percentage_1_train:.2f}%")

# Calculate the percentage of 1s in y_test
percentage_1_test = (y_test == 1).mean() * 100
print(f"Percentage of '1' (spoof) in y_test: {percentage_1_test:.2f}%")

Percentage of '1' (spoof) in y_train: 89.36%
Percentage of '1' (spoof) in y_test: 37.18%

In [81]:
!pip install --upgrade scikit-learn
!pip install --upgrade imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/zkhanja1/.local/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imbalanced-learn in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (0.11.0)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.13.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy<3,>=1.24.3 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy<2,>=1.10.1 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.15.2)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (1.6.1)
Collecting sklearn-compat<1,>=0.1 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: joblib<2,>=1.1.1 in /usr/ebuild/installs/software/Anaconda3/2024.02-1/lib/python3.11/site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /home/zkhanja1/.local/lib/python3.11/site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.13.0-py3-none-any.whl (238 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.4/238.4 kB 5.4 MB/s eta 0:00:00:00:01
Downloading sklearn_compat-0.1.3-py3-none-any.whl (18 kB)
Installing collected packages: sklearn-compat, imbalanced-learn
Successfully installed imbalanced-learn-0.13.0 sklearn-compat-0.1.3

In [98]:
X_train.shape

(7208, 549, 768)

In [97]:
from imblearn.over_sampling import SMOTE

# First, ensure y_train is a numpy array if it's not already
y_train_np = y_train.values if hasattr(y_train, 'values') else y_train

# Apply SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train.reshape(X_train.shape[0], -1), y_train_np)

# If needed, reshape X_train_resampled back to original dimensions
X_train_resampled = X_train_resampled.reshape(-1, X_train.shape[1], X_train.shape[2])

# Print new class distribution
print(f"Resampled class distribution:\n{pd.Series(y_train_resampled).value_counts()}")

ValueError: Found input variables with inconsistent numbers of samples: [7208, 7001]

In [20]:
y_train

0       1
1       0
2       1
3       1
4       1
       ..
6994    1
6995    1
6996    1
6997    1
6998    0
Name: Label, Length: 6999, dtype: int64

In [57]:
X_train_resampled.shape

(12576, 549, 768)

In [21]:
from sklearn.model_selection import train_test_split

# Use 10% of the original X_train and y_train as validation
X_train_sub, X_val, y_train_sub, y_val = train_test_split(
    X_train, y_train, test_size=0.1, random_state=42, stratify=y_train
)

In [22]:
from tensorflow.keras.metrics import AUC

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam

# Flatten input shape for MLP
input_dim = X_train_resampled.shape[1] * X_train_resampled.shape[2]

model = Sequential([
    Flatten(input_shape=(X_train_resampled.shape[1], X_train_resampled.shape[2])),
    Dense(128, activation='relu'),
   # Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.6),
    Dense(1, activation='sigmoid')
])



model.compile(
    optimizer=Adam(learning_rate=0.001), 
    loss='binary_crossentropy', 
    metrics=[AUC(name='roc_auc')]
)

In [80]:
X_val.shape

(700, 1, 549, 768)

In [81]:
y_test

0       1
1       1
2       1
3       1
4       1
       ..
6995    1
6996    1
6997    1
6998    1
6999    1
Name: Label, Length: 7000, dtype: int64

In [82]:
? model

Signature:    model(*args, **kwargs)
Type:        Sequential
String form: <Sequential name=sequential_1, built=True>
File:        ~/.local/lib/python3.11/site-packages/keras/src/models/sequential.py
Docstring:
`Sequential` groups a linear stack of layers into a `Model`.

Examples:

```python
model = keras.Sequential()
model.add(keras.Input(shape=(16,)))
model.add(keras.layers.Dense(8))

# Note that you can also omit the initial `Input`.
# In that case the model doesn't have any weights until the first call
# to a training/evaluation method (since it isn't yet built):
model = keras.Sequential()
model.add(keras.layers.Dense(8))
model.add(keras.layers.Dense(4))
# model.weights not created yet

# Whereas if you specify an `Input`, the model gets built
# continuously as you are adding layers:
model = keras.Sequential()
model.add(keras.Input(shape=(16,)))
model.add(keras.layers.Dense(8))
len(model.weights)  # Returns "2"

# When using the delayed-build pattern (no input shape specified), you can
# choose to manually build your model by calling
# `build(batch_input_shape)`:
model = keras.Sequential()
model.add(keras.layers.Dense(8))
model.add(keras.layers.Dense(4))
model.build((None, 16))
len(model.weights)  # Returns "4"

# Note that when using the delayed-build pattern (no input shape specified),
# the model gets built the first time you call `fit`, `eval`, or `predict`,
# or the first time you call the model on some input data.
model = keras.Sequential()
model.add(keras.layers.Dense(8))
model.add(keras.layers.Dense(1))
model.compile(optimizer='sgd', loss='mse')
# This builds the model for the first time:
model.fit(x, y, batch_size=32, epochs=10)
```

In [24]:
X_val_org = X_val

In [25]:
X_val = X_val_org

In [86]:
X_train_resampled.shape

(12576, 549, 768)

In [26]:
history = model.fit(
    X_train_resampled, y_train_resampled,
    validation_data=(X_val, y_val),
    epochs=50,  # Can adjust epochs
    batch_size=32
)

Epoch 1/50

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1753043792.303545 2145431 service.cc:152] XLA service 0x155428017bb0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1753043792.303602 2145431 service.cc:160]   StreamExecutor device (0): Quadro RTX 8000, Compute Capability 7.5
2025-07-20 16:36:32.858286: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1753043793.536925 2145431 cuda_dnn.cc:529] Loaded cuDNN version 90300

  7/393 ━━━━━━━━━━━━━━━━━━━━ 10s 28ms/step - loss: 15.4374 - roc_auc: 0.6325

I0000 00:00:1753043796.089495 2145431 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - loss: 4.1934 - roc_auc: 0.8520 - val_loss: 0.1024 - val_roc_auc: 0.9914
Epoch 2/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 0.1818 - roc_auc: 0.9820 - val_loss: 0.1036 - val_roc_auc: 0.9976
Epoch 3/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.1183 - roc_auc: 0.9907 - val_loss: 0.0977 - val_roc_auc: 0.9998
Epoch 4/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0720 - roc_auc: 0.9960 - val_loss: 0.3374 - val_roc_auc: 0.9865
Epoch 5/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.1796 - roc_auc: 0.9840 - val_loss: 0.0052 - val_roc_auc: 1.0000
Epoch 6/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0445 - roc_auc: 0.9982 - val_loss: 0.0854 - val_roc_auc: 0.9981
Epoch 7/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 30ms/step - loss: 0.0561 - roc_auc: 0.9975 - val_loss: 0.0060 - val_roc_auc: 1.0000
Epoch 8/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - loss: 0.0303 - roc_auc: 0.9992 - val_loss: 0.0029 - val_roc_auc: 1.0000
Epoch 9/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0384 - roc_auc: 0.9985 - val_loss: 0.0046 - val_roc_auc: 1.0000
Epoch 10/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0257 - roc_auc: 0.9994 - val_loss: 0.0154 - val_roc_auc: 0.9999
Epoch 11/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 21s 30ms/step - loss: 0.0377 - roc_auc: 0.9983 - val_loss: 0.0070 - val_roc_auc: 1.0000
Epoch 12/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - loss: 0.0393 - roc_auc: 0.9982 - val_loss: 0.0219 - val_roc_auc: 0.9991
Epoch 13/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0474 - roc_auc: 0.9973 - val_loss: 6.0270e-04 - val_roc_auc: 1.0000
Epoch 14/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0071 - roc_auc: 0.9998 - val_loss: 2.2569e-04 - val_roc_auc: 1.0000
Epoch 15/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0134 - roc_auc: 0.9994 - val_loss: 0.0831 - val_roc_auc: 0.9718
Epoch 16/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.0263 - roc_auc: 0.9987 - val_loss: 1.4177e-04 - val_roc_auc: 1.0000
Epoch 17/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - loss: 0.0016 - roc_auc: 1.0000 - val_loss: 2.4490e-05 - val_roc_auc: 1.0000
Epoch 18/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0163 - roc_auc: 0.9994 - val_loss: 1.7476e-06 - val_roc_auc: 1.0000
Epoch 19/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 21s 30ms/step - loss: 0.0383 - roc_auc: 0.9980 - val_loss: 0.0015 - val_roc_auc: 1.0000
Epoch 20/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0220 - roc_auc: 0.9995 - val_loss: 0.0462 - val_roc_auc: 0.9984
Epoch 21/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0103 - roc_auc: 0.9999 - val_loss: 2.7372e-07 - val_roc_auc: 1.0000
Epoch 22/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0047 - roc_auc: 1.0000 - val_loss: 7.8825e-10 - val_roc_auc: 1.0000
Epoch 23/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0028 - roc_auc: 1.0000 - val_loss: 7.4966e-07 - val_roc_auc: 1.0000
Epoch 24/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 30ms/step - loss: 0.0017 - roc_auc: 1.0000 - val_loss: 8.5300e-04 - val_roc_auc: 1.0000
Epoch 25/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0394 - roc_auc: 0.9977 - val_loss: 0.0025 - val_roc_auc: 1.0000
Epoch 26/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 21s 29ms/step - loss: 0.0119 - roc_auc: 0.9999 - val_loss: 2.4150e-06 - val_roc_auc: 1.0000
Epoch 27/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0016 - roc_auc: 1.0000 - val_loss: 1.2831e-07 - val_roc_auc: 1.0000
Epoch 28/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - loss: 0.0128 - roc_auc: 0.9996 - val_loss: 0.0043 - val_roc_auc: 1.0000
Epoch 29/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0136 - roc_auc: 0.9999 - val_loss: 3.0723e-05 - val_roc_auc: 1.0000
Epoch 30/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 21s 30ms/step - loss: 0.0058 - roc_auc: 0.9999 - val_loss: 0.0104 - val_roc_auc: 0.9930
Epoch 31/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - loss: 0.0200 - roc_auc: 0.9993 - val_loss: 2.4054e-05 - val_roc_auc: 1.0000
Epoch 32/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0026 - roc_auc: 1.0000 - val_loss: 5.7316e-07 - val_roc_auc: 1.0000
Epoch 33/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0018 - roc_auc: 1.0000 - val_loss: 1.4460e-08 - val_roc_auc: 1.0000
Epoch 34/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0088 - roc_auc: 0.9996 - val_loss: 1.8803e-04 - val_roc_auc: 1.0000
Epoch 35/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0031 - roc_auc: 0.9999 - val_loss: 2.1498e-06 - val_roc_auc: 1.0000
Epoch 36/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0068 - roc_auc: 0.9998 - val_loss: 1.3769e-08 - val_roc_auc: 1.0000
Epoch 37/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0061 - roc_auc: 0.9997 - val_loss: 0.0185 - val_roc_auc: 0.9992
Epoch 38/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 30ms/step - loss: 0.0130 - roc_auc: 0.9994 - val_loss: 3.4475e-05 - val_roc_auc: 1.0000
Epoch 39/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - loss: 0.0015 - roc_auc: 1.0000 - val_loss: 1.1606e-06 - val_roc_auc: 1.0000
Epoch 40/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 30ms/step - loss: 8.6193e-04 - roc_auc: 1.0000 - val_loss: 4.2475e-07 - val_roc_auc: 1.0000
Epoch 41/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 7.1487e-04 - roc_auc: 1.0000 - val_loss: 3.6679e-05 - val_roc_auc: 1.0000
Epoch 42/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 30ms/step - loss: 0.0186 - roc_auc: 0.9992 - val_loss: 0.0013 - val_roc_auc: 1.0000
Epoch 43/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0077 - roc_auc: 0.9999 - val_loss: 1.3690e-04 - val_roc_auc: 1.0000
Epoch 44/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0031 - roc_auc: 1.0000 - val_loss: 1.9208e-05 - val_roc_auc: 1.0000
Epoch 45/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 12s 29ms/step - loss: 0.0012 - roc_auc: 1.0000 - val_loss: 3.3873e-07 - val_roc_auc: 1.0000
Epoch 46/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0073 - roc_auc: 0.9995 - val_loss: 4.2784e-06 - val_roc_auc: 1.0000
Epoch 47/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 21s 30ms/step - loss: 0.0014 - roc_auc: 1.0000 - val_loss: 2.2793e-06 - val_roc_auc: 1.0000
Epoch 48/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0011 - roc_auc: 1.0000 - val_loss: 1.4597e-08 - val_roc_auc: 1.0000
Epoch 49/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0014 - roc_auc: 1.0000 - val_loss: 9.4665e-08 - val_roc_auc: 1.0000
Epoch 50/50
393/393 ━━━━━━━━━━━━━━━━━━━━ 20s 29ms/step - loss: 0.0177 - roc_auc: 0.9993 - val_loss: 7.9165e-05 - val_roc_auc: 1.0000

In [84]:
# I have reshaped all and applied ResNet 18, now wanna reshape them to their original
X_train_resampled = np.squeeze(X_train_resampled, axis=1)
X_val = np.squeeze(X_val, axis=1)
X_train = np.squeeze(X_train, axis=1)
X_test = np.squeeze(X_test, axis=1)

In [ ]:
l

In [27]:
# Get probabilities for original X_train and X_test
probs_train = model.predict(X_train)
probs_test = model.predict(X_test)

print(f"First 5 probabilities on X_train:\n{probs_train[:5].flatten()}")
print(f"First 5 probabilities on X_test:\n{probs_test[:5].flatten()}")

219/219 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step
219/219 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step
First 5 probabilities on X_train:
[1.0000000e+00 1.7555061e-08 1.0000000e+00 1.0000000e+00 1.0000000e+00]
First 5 probabilities on X_test:
[1. 1. 1. 1. 1.]

In [67]:
len(X_test)

7000

In [68]:
y_test

0       1
1       1
2       1
3       1
4       1
       ..
6995    1
6996    1
6997    1
6998    1
6999    1
Name: Label, Length: 7000, dtype: int64

In [29]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on training data: 1.0000
ROC AUC on test data: 0.7773

In [58]:
probs_test

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [70]:
unique_values = np.unique(probs_test)
print(unique_values)

[1.09633821e-31 1.20024500e-30 1.22177708e-29 8.26680331e-29
 3.63638444e-28 6.43211483e-26 6.91474979e-26 2.50600284e-24
 2.73384717e-24 3.40323666e-24 3.53937315e-24 4.98056957e-24
 8.54608044e-24 1.99615509e-23 4.23137732e-23 4.33702915e-23
 4.86133860e-23 7.59687125e-23 9.29578444e-22 9.91151801e-22
 1.37750149e-21 1.39900698e-21 1.90721858e-21 9.53731088e-21
 1.21794364e-20 1.33076825e-20 3.46520757e-20 6.13066010e-20
 7.45853313e-20 9.73734011e-20 1.40437703e-19 1.59069404e-19
 5.50222345e-19 1.01747579e-18 1.30567761e-18 2.61015643e-18
 3.55613838e-18 4.43657163e-18 4.74059318e-18 9.28545558e-18
 9.61172457e-18 1.02504966e-17 1.35940591e-17 1.90344284e-17
 2.03337439e-17 3.09411011e-17 4.22890530e-17 4.93562988e-17
 1.15640114e-16 1.16580440e-16 1.71168603e-16 1.80908053e-16
 3.07908758e-16 4.82137242e-16 6.03270153e-16 7.08205994e-16
 1.01068437e-15 1.28746372e-15 1.31853288e-15 1.49626115e-15
 1.59104297e-15 1.62473995e-15 1.94850189e-15 3.13973472e-15
 5.46029159e-15 2.29870190e-14 2.33897069e-14 2.73850597e-14
 4.74752480e-14 7.12989712e-14 1.83850114e-13 5.16862052e-13
 7.67645279e-13 1.22763215e-12 2.22600540e-12 5.54536668e-12
 8.18633442e-12 9.60420372e-12 1.10261531e-11 2.16203028e-11
 6.27282948e-11 7.21370602e-11 3.84935944e-10 6.37606579e-10
 7.43595741e-10 8.09015077e-10 1.89736848e-09 2.83338641e-09
 3.84508336e-09 4.68591210e-09 6.84539092e-09 8.90652352e-09
 1.49507109e-08 2.23090648e-08 3.20578408e-08 4.17391206e-08
 4.39780514e-08 4.48466366e-08 4.74550248e-08 6.63422668e-08
 1.18342214e-07 1.33911072e-07 1.51239789e-07 2.04289705e-07
 3.91724541e-07 3.98877717e-07 6.54839880e-07 6.68836321e-07
 1.05703452e-06 1.09661335e-06 1.63064499e-06 1.68261261e-06
 2.09679388e-06 3.47104105e-06 4.68065446e-06 5.40592873e-06
 6.08200526e-06 7.87379304e-06 9.92839796e-06 1.67094495e-05
 2.04187218e-05 2.09522641e-05 2.55625146e-05 3.29961076e-05
 3.42133717e-05 3.97181248e-05 4.58720497e-05 4.71666754e-05
 5.39814246e-05 1.08277396e-04 1.26902713e-04 1.41092140e-04
 4.02022386e-04 4.32938832e-04 4.40584030e-04 5.72158722e-04
 7.13159214e-04 7.55664834e-04 1.24352670e-03 1.48619921e-03
 1.71549956e-03 1.77072524e-03 3.23410588e-03 3.93137010e-03
 4.27863700e-03 1.08869998e-02 2.17344798e-02 2.22541392e-02
 2.26329360e-02 2.55639385e-02 6.67738840e-02 7.05886558e-02
 9.52380374e-02 1.23543970e-01 1.84391126e-01 2.60807246e-01
 2.73115367e-01 4.36016470e-01 4.63324875e-01 5.12815833e-01
 5.46880543e-01 5.77086270e-01 6.03214502e-01 6.29489064e-01
 6.94933474e-01 7.54878581e-01 8.13252807e-01 8.75890553e-01
 8.96690488e-01 8.97016823e-01 9.33518469e-01 9.54119265e-01
 9.60745811e-01 9.64749932e-01 9.65755463e-01 9.68938708e-01
 9.70090270e-01 9.75085497e-01 9.76869047e-01 9.81936157e-01
 9.83045161e-01 9.84885633e-01 9.86110687e-01 9.90940690e-01
 9.91037965e-01 9.92624938e-01 9.92831230e-01 9.94916499e-01
 9.95193779e-01 9.95513976e-01 9.96642709e-01 9.96986449e-01
 9.98001635e-01 9.98119652e-01 9.98235941e-01 9.99408960e-01
 9.99445379e-01 9.99764264e-01 9.99766529e-01 9.99791265e-01
 9.99836564e-01 9.99858022e-01 9.99915123e-01 9.99920845e-01
 9.99952316e-01 9.99958038e-01 9.99979496e-01 9.99983072e-01
 9.99990940e-01 9.99991298e-01 9.99992847e-01 9.99993086e-01
 9.99998093e-01 9.99999285e-01 9.99999404e-01 9.99999523e-01
 9.99999642e-01 9.99999762e-01 9.99999881e-01 1.00000000e+00]

In [71]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

159

MLP is okay but will use the resnet too.
a ResNet18 as classifier. We train all of our systems with a cross-entropy loss. We use Adam optimizer with fixed learning rate at 1e-4 and weight decay at 1e-4. We train all the systems 20 epochs.

 Please note: Since ResNet-18 expects images (3D tensors), we need to ensure that:

    X_train_resampled, X_val, X_train, and X_test are reshaped to (samples, channels, height, width).

    I will do for 25 epochs instead of 100

In [72]:
# Assuming X_train shape is (samples, time_steps, features)
X_train_resampled = np.expand_dims(X_train_resampled, axis=1)  # (samples, 1, time_steps, features)
X_val = np.expand_dims(X_val, axis=1)
X_train = np.expand_dims(X_train, axis=1)
X_test = np.expand_dims(X_test, axis=1)

In [73]:
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

def build_resnet18(input_shape):
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2D(64, 7, strides=2, padding='same', use_bias=False)(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D(3, strides=2, padding='same')(x)

    def residual_block(x, filters, downsample=False):
        shortcut = x
        strides = 2 if downsample else 1
        x = layers.Conv2D(filters, 3, strides=strides, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)
        x = layers.ReLU()(x)
        x = layers.Conv2D(filters, 3, strides=1, padding='same', use_bias=False,
                          kernel_regularizer=regularizers.l2(1e-4))(x)
        x = layers.BatchNormalization()(x)

        if downsample or shortcut.shape[-1] != filters:
            shortcut = layers.Conv2D(filters, 1, strides=strides, padding='same', use_bias=False,
                                     kernel_regularizer=regularizers.l2(1e-4))(shortcut)
            shortcut = layers.BatchNormalization()(shortcut)

        x = layers.add([x, shortcut])
        x = layers.ReLU()(x)
        return x

    x = residual_block(x, 64)
    x = residual_block(x, 64)
    x = residual_block(x, 128, downsample=True)
    x = residual_block(x, 128)
    x = residual_block(x, 256, downsample=True)
    x = residual_block(x, 256)
    x = residual_block(x, 512, downsample=True)
    x = residual_block(x, 512)

    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(1, activation='sigmoid')(x)

    model = models.Model(inputs, outputs)
    return model

input_shape = X_train_resampled.shape[1:]  # (time_steps, features, 1)
resnet18_model = build_resnet18(input_shape)

In [74]:
from tensorflow.keras.optimizers import Adam

resnet18_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=[tf.keras.metrics.AUC(name='roc_auc')]
)

In [75]:
history = resnet18_model.fit(
    X_train_resampled, y_train_resampled,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=64
)

Epoch 1/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - loss: 0.5629 - roc_auc: 0.9611 - val_loss: 3.2156 - val_roc_auc: 0.9192
Epoch 2/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - loss: 0.2262 - roc_auc: 0.9996 - val_loss: 3.8593 - val_roc_auc: 0.8521
Epoch 3/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 0.1939 - roc_auc: 0.9998 - val_loss: 0.3650 - val_roc_auc: 0.9988
Epoch 4/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 28ms/step - loss: 0.1774 - roc_auc: 1.0000 - val_loss: 0.1798 - val_roc_auc: 0.9999
Epoch 5/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1782 - roc_auc: 0.9998 - val_loss: 0.1651 - val_roc_auc: 1.0000
Epoch 6/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1682 - roc_auc: 1.0000 - val_loss: 0.1630 - val_roc_auc: 1.0000
Epoch 7/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1620 - roc_auc: 1.0000 - val_loss: 0.1907 - val_roc_auc: 1.0000
Epoch 8/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1579 - roc_auc: 1.0000 - val_loss: 0.1620 - val_roc_auc: 1.0000
Epoch 9/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1512 - roc_auc: 1.0000 - val_loss: 0.1506 - val_roc_auc: 1.0000
Epoch 10/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1565 - roc_auc: 0.9996 - val_loss: 0.1423 - val_roc_auc: 1.0000
Epoch 11/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1427 - roc_auc: 1.0000 - val_loss: 0.1486 - val_roc_auc: 1.0000
Epoch 12/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1366 - roc_auc: 1.0000 - val_loss: 0.1304 - val_roc_auc: 1.0000
Epoch 13/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1307 - roc_auc: 0.9999 - val_loss: 0.1264 - val_roc_auc: 1.0000
Epoch 14/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1270 - roc_auc: 1.0000 - val_loss: 0.1200 - val_roc_auc: 1.0000
Epoch 15/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1190 - roc_auc: 1.0000 - val_loss: 0.1161 - val_roc_auc: 1.0000
Epoch 16/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1184 - roc_auc: 1.0000 - val_loss: 0.1684 - val_roc_auc: 0.9930
Epoch 17/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1144 - roc_auc: 0.9998 - val_loss: 0.1851 - val_roc_auc: 0.9989
Epoch 18/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.1115 - roc_auc: 0.9995 - val_loss: 0.1004 - val_roc_auc: 1.0000
Epoch 19/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0995 - roc_auc: 1.0000 - val_loss: 0.0959 - val_roc_auc: 1.0000
Epoch 20/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0943 - roc_auc: 1.0000 - val_loss: 0.0903 - val_roc_auc: 1.0000
Epoch 21/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0894 - roc_auc: 1.0000 - val_loss: 0.0885 - val_roc_auc: 1.0000
Epoch 22/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0910 - roc_auc: 0.9999 - val_loss: 0.0828 - val_roc_auc: 1.0000
Epoch 23/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0829 - roc_auc: 1.0000 - val_loss: 0.0784 - val_roc_auc: 1.0000
Epoch 24/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 27ms/step - loss: 0.0771 - roc_auc: 1.0000 - val_loss: 0.0739 - val_roc_auc: 1.0000
Epoch 25/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0730 - roc_auc: 1.0000 - val_loss: 0.0704 - val_roc_auc: 1.0000
Epoch 26/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0697 - roc_auc: 1.0000 - val_loss: 0.0989 - val_roc_auc: 0.9929
Epoch 27/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0700 - roc_auc: 0.9997 - val_loss: 0.0631 - val_roc_auc: 1.0000
Epoch 28/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0638 - roc_auc: 1.0000 - val_loss: 0.0743 - val_roc_auc: 1.0000
Epoch 29/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0607 - roc_auc: 1.0000 - val_loss: 0.0572 - val_roc_auc: 1.0000
Epoch 30/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0606 - roc_auc: 0.9999 - val_loss: 0.0605 - val_roc_auc: 1.0000
Epoch 31/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0547 - roc_auc: 1.0000 - val_loss: 0.0533 - val_roc_auc: 1.0000
Epoch 32/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0517 - roc_auc: 1.0000 - val_loss: 0.0494 - val_roc_auc: 1.0000
Epoch 33/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0493 - roc_auc: 1.0000 - val_loss: 0.0467 - val_roc_auc: 1.0000
Epoch 34/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0462 - roc_auc: 1.0000 - val_loss: 0.0443 - val_roc_auc: 1.0000
Epoch 35/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0436 - roc_auc: 1.0000 - val_loss: 0.0421 - val_roc_auc: 1.0000
Epoch 36/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 27ms/step - loss: 0.0412 - roc_auc: 1.0000 - val_loss: 0.0409 - val_roc_auc: 1.0000
Epoch 37/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0405 - roc_auc: 1.0000 - val_loss: 0.0569 - val_roc_auc: 0.9930
Epoch 38/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0408 - roc_auc: 0.9999 - val_loss: 3.2643 - val_roc_auc: 0.5141
Epoch 39/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0450 - roc_auc: 0.9999 - val_loss: 0.0405 - val_roc_auc: 1.0000
Epoch 40/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0383 - roc_auc: 1.0000 - val_loss: 0.0352 - val_roc_auc: 1.0000
Epoch 41/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0349 - roc_auc: 1.0000 - val_loss: 0.0334 - val_roc_auc: 1.0000
Epoch 42/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0330 - roc_auc: 1.0000 - val_loss: 0.0328 - val_roc_auc: 1.0000
Epoch 43/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0327 - roc_auc: 0.9999 - val_loss: 0.0306 - val_roc_auc: 1.0000
Epoch 44/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0308 - roc_auc: 1.0000 - val_loss: 0.0294 - val_roc_auc: 1.0000
Epoch 45/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0289 - roc_auc: 1.0000 - val_loss: 0.0281 - val_roc_auc: 1.0000
Epoch 46/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0276 - roc_auc: 1.0000 - val_loss: 0.0267 - val_roc_auc: 1.0000
Epoch 47/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0282 - roc_auc: 1.0000 - val_loss: 0.0264 - val_roc_auc: 1.0000
Epoch 48/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0276 - roc_auc: 1.0000 - val_loss: 0.0253 - val_roc_auc: 1.0000
Epoch 49/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0252 - roc_auc: 1.0000 - val_loss: 0.0295 - val_roc_auc: 1.0000
Epoch 50/50
197/197 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - loss: 0.0252 - roc_auc: 1.0000 - val_loss: 1.6586 - val_roc_auc: 0.6127

In [77]:
probs_train = resnet18_model.predict(X_train).flatten()
probs_test = resnet18_model.predict(X_test).flatten()

print(f"First 5 probabilities (train): {probs_train[:5]}")
print(f"First 5 probabilities (test): {probs_test[:5]}")

219/219 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step
First 5 probabilities (train): [1.        0.9989274 1.        1.        1.       ]
First 5 probabilities (test): [1. 1. 1. 1. 1.]

In [78]:
from sklearn.metrics import roc_auc_score

# Calculate ROC AUC for train
roc_auc_train = roc_auc_score(y_train, probs_train)
print(f"ROC AUC on training data: {roc_auc_train:.4f}")

# Calculate ROC AUC for test
roc_auc_test = roc_auc_score(y_test, probs_test)
print(f"ROC AUC on test data: {roc_auc_test:.4f}")

ROC AUC on training data: 0.8010
ROC AUC on test data: 0.6281

Ooops! Interesting! Although HuBERT and WAVLM are almost the same (WavLM is an edition on HuBERT), WavLM is worse when used ResNet18, and I gonna save the MLP results

In [30]:
df_train_preds = pd.DataFrame({
    'audio_filenames': y_train_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_train.flatten()
})

In [31]:
df_train_preds

     audio_filenames    prob_spoof
0       LA_T_1000137  1.000000e+00
1       LA_T_1000406  1.755506e-08
2       LA_T_1000648  1.000000e+00
3       LA_T_1000824  1.000000e+00
4       LA_T_1001074  1.000000e+00
...              ...           ...
6994    LA_T_3469583  1.000000e+00
6995    LA_T_3469591  1.000000e+00
6996    LA_T_3469711  1.000000e+00
6997    LA_T_3470036  1.000000e+00
6998    LA_T_3470152  2.907453e-12

[6999 rows x 2 columns]

In [32]:
# Save train predictions
df_train_preds.to_csv('train_predictions_wavlm_mlp_7000_df.csv', index=False)

In [78]:
len(y_test_new)

6998

In [33]:
count_under_ = np.sum(probs_test < 0.5)
print(count_under_)

168

In [34]:
# Create DataFrame for test predictions
df_test_preds = pd.DataFrame({
    'audio_filenames': y_test_new['audio_filenames'],  # or appropriate filenames list
    'prob_spoof': probs_test.flatten()
})

In [35]:
df_test_preds

     audio_filenames  prob_spoof
0       DF_E_2000011         1.0
1       DF_E_2000013         1.0
2       DF_E_2000024         1.0
3       DF_E_2000026         1.0
4       DF_E_2000027         1.0
...              ...         ...
6995    DF_E_2034401         1.0
6996    DF_E_2034402         1.0
6997    DF_E_2034405         1.0
6998    DF_E_2034408         1.0
6999    DF_E_2034413         1.0

[7000 rows x 2 columns]

In [36]:
# Save test predictions
df_test_preds.to_csv('test_predictions_wavlm_mlp_7000_df.csv', index=False)